### ISSUE TITLE
Move gov handler to x/gov message execution

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1001]
Function handlers for x/gov are deprecated since 0.46. We should migrated the handlers to the new x/gov messages. Can be done in 2 PRs or in one:
- [ ] migrate x/leverage handlers
- [ ] migrate x/oracle handlers.

**Comment by toteki** [comment]
Adding to calypso milestone since 0.46 gov handlers should be included in that upgrade

**Comment by robert-zaremba** [comment]
good idea. I'm tracking it in github projects.

**Comment by robert-zaremba** [comment]
Need to check. I thought we have one in oracle, but indeed, in https://github.com/umee-network/umee/blob/main/app/app.go#L500 we only register leverage.

**Comment by robert-zaremba** [comment]
> cli txn for leverage

Not needed, because it's handled by `umeed tx gov submit-proposal path/to/proposal.json`
Instead we can update docs.
