### ISSUE TITLE
docs: Standardize ADRs

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#1035]
ADR documents for leverage module have mostly not been modified since their creation.

In practice, our ADR documents have been created before module implementation and spec writing, and vary in level of detail provided.

Steps for improvement:
- Remove my nooby commentary from my early ADRs which would be self-evident to a cosmos dev (e.g. describing bank module capabilities in 002)
- Remove any non-useful "alternative approaches" and "open questions" entries, and add current open questions
- Standardize message and state data model blocks to protobuf as @robert-zaremba suggested in 009's PR
- Focus on practical effects of functions, removing pedantic implementation details
- Increase level of mathematical analysis and core concepts coverage, some of which is currently better in module spec
- Increase example scenarios where appropriate
- Link to related ADRs in status, e.g. in ADR-003 (borrow assets):

```
## Status

Implemented

Partially superseded by [ADR-007](./ADR-008-borrow-tracking.md)
```

**Comment by adamewozniak** [comment]
Using some of the images from the ToB / runtime verification audits would be super good here too 🥳

**Comment by toteki** [comment]
Closing this issue in favor of #1112 (partial duplicate)
