### ISSUE TITLE
Use MaxCollateralUtilization or MinCollateralLiquidity in interest rate calculation

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1037]
Depends on:
+ https://github.com/umee-network/umee/issues/1036

## Summary

In https://github.com/umee-network/umee/pull/940 we introduced `MaxCollateralUtilization` and decided to use it for interest rates instead for _supply utilization_.

* update algorithm
* update tests
* make sure borrows are not possible if collateral utilization goes above max collateral utilization

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
This can be closed - interest rates will still be based on _borrow utilization_, not collateral utilization.

Even assets with collateral weight = 0 (cannot be collateralized) need dynamic interest rates.

**Comment by robert-zaremba** [comment]
Today we have supply_utilization not borrow_utilization.

I think we should consider changing interest rates base on borrow_utilization (the new model)
