### ISSUE TITLE
Internal x/oracle audit

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1046]
## Summary

We have sync issue and we are investigating from all different fronts where the sync issues comes from.

## Proposal

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
@robert-zaremba can we close this out, now that we know the sync issue was caused by the price feeder's constant querying?
