### ISSUE TITLE
Umeed Export outputs a zero-byte-length genesis file

### ISSUE THREAD

**Issue by dreamcodez** [umee-network/umee#1051]
## Summary of Bug

Umeed Export outputs a zero-byte-length genesis file

## Version

Please provide the output of the following commands:

- `$ umeed version` `2.0.3-rc2`
- `$ go version` `N/A (ci version 1.18)`
- `$ uname -a` `Linux festival 5.13.0-1033-gcp #40~20.04.1-Ubuntu SMP Tue Jun 14 00:44:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

## Steps to Reproduce

1. `umeed export > export.json` (from a populated node in umeemania-1)
2.  once complete, notice that output file is 0 bytes in length

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RafilxTenfen** [comment]
duplicated from #914?
Closing this, since it will be solved in cosmos-sdk 0.46 and right now could be done using stderr like: `umeed export 2> export.json`
