### ISSUE TITLE
--cosmos-grpc does not work for custom port (Umeemania Testnet)

### ISSUE THREAD

**Issue by lightiv** [umee-network/umee#1067]
## Summary of Bug

Using `--cosmos-grpc` to assign an custom gRPC port did not work.   I would receive:
```
Waiting for cosmos gRPC service...
state of gRPC connection not ready: TRANSIENT_FAILURE
```

## Version

Please provide the output of the following commands:

- `$ umeed version` HEAD-86842a207ab7868c3073a6734d72b25cf768cbe6
- `$ go version`  v1.18
- `$ uname -a` Linux t-grade-validator 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

## Steps to Reproduce

1. Set gRPC in app.toml to a non-9090/9091 port number and restart umeed

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RafilxTenfen** [comment]
flag `--cosmos-grpc` is for [peggo](https://github.com/umee-network/peggo) :thinking: 
On umee you can set `[grpc] address` in `.umee/config/app.toml` or overwrite that with `--grpc.address` 
check the available flags with `umeed start --help` 

Closing this for now
