### ISSUE TITLE
x/leverage: Total Borrowed and Total Supplied queries

### ISSUE THREAD

**Issue by brandoncomer** [umee-network/umee#1071]
Frontend team is requesting 4 queries: 

- total borrows by denom (in USD)
- total borrows by denom (in tokens)
- total supply by denom (in USD)
- total supply by denom (in tokens)

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
let's add it to the blockchain project.
