### ISSUE TITLE
Price-feeder: Allow quote-specific deviation detection

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#1083]
## Problem Definition

Right now, our deviation detection assumes that any base asset we're trying to get the price of is all configured to use the same or similar exchange rates (e.g., ETH/USD vs ETH/USDT). In order to support more assets, we should add context for other pairs.

As an example, if we had three exchange rates for BTC, two as BTC/USD, and one as BTC/ETH, with exchange rates for ETH/USD, the price feeder filters out the BTC/ETH price.

## Proposal

We need to be able to support getting an asset's price with multiple quotes, such as using ETH/USD, ETH/BTC, and BTC/USD at once. 

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
This is a **must** for mainnet to support more assets.

**Comment by robert-zaremba** [comment]
why it's a _must_? It seams that it will shift the computation from the price feeder to the chain for doing that stuff, without necessary adding real data... in other words - most of the data points will be derived anyway.

**Comment by adamewozniak** [comment]
@robert-zaremba this is still in the price feeder, just changes the loop a bit - some assets that we're planning on adding for mainnet don't have enough stablecoin pairs to support the way we're currently doing deviation. Right now we just assume everything is in stables or USD, but we need to be able to go from BTC/ETH to BTC/USD
