### ISSUE TITLE
proto: consider Borrower and Lender Fields

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#1103]
For `MsgSupply`, the `Lender` (or `Supplier` after rename) field can be renamed to `FromAddress` or just `Address`.

Similar applies to `MsgAddCollateral` for example, which has `Lender` field.

Is standardizing these address fields in message types worth doing?

**Comment by robert-zaremba** [comment]
I prefer `Supplier` or `Sender`. `Address` doesn't make much meaning.
