### ISSUE TITLE
feat: exchange rate tracking EndBlock events for leverage and oracle

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#1109]
To make it easier for analytics to associate transactions with historical oracle prices and uToken exchange rates, we can create events at `EndBlock` for the two modules, which simply record the set of current values for all accepted tokens.

**Comment by adamewozniak** [comment]
We can likely just send events from x/oracle at the end of each voting period - I'll pick this one up since I'd like to see how they're working anyways 😄

**Comment by adamewozniak** [comment]
Turns out I already [put this in](https://github.com/umee-network/umee/blob/218ffbacbf0ee64aa0f52f7c09d00961938a5c5f/x/oracle/keeper/keeper.go#L128) a while ago 😅 the events are of the type `exchange_rate_update`
cc: @toteki @khoerling
