### ISSUE TITLE
Price-feeder: Add acceptable asset quote list

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#1117]
## Summary

Context: https://github.com/umee-network/umee/pull/1110#issuecomment-1177991371

We should only allow prices to be quoted in USD, USDT, ETH, BTC, and ATOM

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
To be more precise:
1. Atom should be taken into account if it has significant volume (otherwise it's likely a secondary market for arbitrage)
2. Need to think if we need both ETH and BTC

**Comment by adamewozniak** [comment]
Adding USDC to this 👍

**Comment by adamewozniak** [comment]
I think initially I'm going to restrict this to quotes in USD, USDT, USDC, ETH, and BTC. Atom does not seem to be very much needed atm and also will cause some headache in the implementation (specifically in which min volume we should apply)

**Comment by robert-zaremba** [comment]
Atom is more used as a base currency in Osmosis than USDC or Eth for example.
So the idea was to be able to add more base currencies per token. So by default we have USDC, USDT, maybe BTC, and then for some tokens we will have Eth extra, for others we will have Atom extra

**Comment by adamewozniak** [comment]
@robert-zaremba gotcha. We don't have to measure volume programmatically then, we can just hardcode the assets that make sense

**Comment by RafilxTenfen** [comment]
can this be not fully mandatory? Like in the peggo perspective, maybe it makes sense to quote in different coins

**Comment by adamewozniak** [comment]
> can this be not fully mandatory? Like in the peggo perspective, maybe it makes sense to quote in different coins

This is currently enforced at the config, which peggo's API shouldn't be limited by 👍

**Comment by adamewozniak** [comment]
Closing this - I don't think handling this programmatically is effective.
