### ISSUE TITLE
Update wasmd to v0.27

### ISSUE THREAD

**Issue by RafilxTenfen** [umee-network/umee#1119]
## Summary
- Currently wasmd in being audit on v0.27, we should upgrade to this version

## Problem Definition
- They updated the ibc-go to v3, we need that too to upgrade 
> It is going to be available after upgrading to SDK 0.46

## Proposal

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
Done in #1547
