### ISSUE TITLE
Staking tx fails when I try to delegate uumee to my node

### ISSUE THREAD

**Issue by ditercry** [umee-network/umee#114]
## Summary of Bug

Transaction fails with an error when I try to delegate tokens to my node
## Version

Please provide the output of the following commands:

- `$ umeed version` v0.2.0
- `$ go version` go version go1.16.5 linux/amd64
- `$ uname -a` Linux umee-val 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- 
## Preconditions:
  address: umee18lvkd9t9ztvsrkkfl8p6crcucpw2e6qkq2a8s6
  valoper: umeevaloper18lvkd9t9ztvsrkkfl8p6crcucpw2e6qkqw6gps

## Steps to Reproduce
1. check balance: 1989719816uumee
2. make transaction: umeed tx staking delegate umeevaloper18lvkd9t9ztvsrkkfl8p6crcucpw2e6qkqw6gps 1979719816uumee --gas auto --chain-id $UMEE_CHAIN --from $UMEE_WALLET --fees=1000uumee
3. Enter keyring passphrase

## Actual result:
`Error: rpc error: code = InvalidArgument desc = recovered: calculated final stake for delegator umee18lvkd9t9ztvsrkkfl8p6crcucpw2e6qkq2a8s6 greater than current stake
        final stake:    9002472762.000000000000000000
        current stake:  8975493762.000000000000000000
stack:
goroutine 52212854 [running]:
runtime/debug.Stack(0x40db9b, 0xc01c0d5a10, 0x18)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1(0x1c04900, 0xc017fb59f0, 0x0, 0xc00bc7cba8)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/recovery.go:71 +0x26
github.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1(0x1c04900, 0xc017fb59f0, 0x0, 0x0, 0xc0000aa2a0)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/recovery.go:39 +0x42
github.com/cosmos/cosmos-sdk/baseapp.processRecovery(0x1c04900, 0xc017fb59f0, 0xc0000aa2a0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/recovery.go:28 +0x43
github.com/cosmos/cosmos-sdk/baseapp.processRecovery(0x1c04900, 0xc017fb59f0, 0xc01c0d5a10, 0x23d4e00, 0xc00aa70340)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/recovery.go:33 +0x85
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1(0xc00bc839c8, 0xc00bc83eb0, 0xc0001dc000, 0xc00bc85928, 0xc00bc85920, 0xc00bc85910)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/baseapp.go:598 +0x1b0
panic(0x1c04900, 0xc017fb59f0)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.CalculateDelegationRewards(0x239e490, 0xc000e48490, 0x23d2338, 0xc000f91290, 0x23d2338, 0xc000f91290, 0xc00000f098, 0x239e490, 0xc000e484c0, 0x239e4e0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/x/distribution/keeper/delegation.go:127 +0x8c5
github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.withdrawDelegationRewards(0x239e490, 0xc000e48490, 0x23d2338, 0xc000f91290, 0x23d2338, 0xc000f91290, 0xc00000f098, 0x239e490, 0xc000e484c0, 0x239e4e0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/x/distribution/keeper/delegation.go:147 +0x2c5
github.com/cosmos/cosmos-sdk/x/distribution/keeper.Hooks.BeforeDelegationSharesModified(0x239e490, 0xc000e48490, 0x23d2338, 0xc000f91290, 0x23d2338, 0xc000f91290, 0xc00000f098, 0x239e490, 0xc000e484c0, 0x239e4e0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/x/distribution/keeper/hooks.go:89 +0x228
github.com/cosmos/cosmos-sdk/x/staking/types.MultiStakingHooks.BeforeDelegationSharesModified(0xc00178b2c0, 0x3, 0x3, 0x23bbbe8, 0xc000098010, 0x23d4e00, 0xc00aa70680, 0xb, 0x0, 0xc013bcf8c0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/x/staking/types/hooks.go:46 +0xf5
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.BeforeDelegationSharesModified(...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/x/staking/keeper/hooks.go:56
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.Delegate(0x239e490, 0xc000e48470, 0x23d2338, 0xc000f91290, 0x23bfee0, 0xc000fc22d0, 0x7f8d3a6f7040, 0xc000be5e40, 0x23d1d90, 0xc0000aa3c0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/x/staking/keeper/delegation.go:566 +0x105d
github.com/cosmos/cosmos-sdk/x/staking/keeper.msgServer.Delegate(0x239e490, 0xc000e48470, 0x23d2338, 0xc000f91290, 0x23bfee0, 0xc000fc22d0, 0x7f8d3a6f7040, 0xc000be5e40, 0x23d1d90, 0xc0000aa3c0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/x/staking/keeper/msg_server.go:214 +0x745
github.com/cosmos/cosmos-sdk/x/staking/types._Msg_Delegate_Handler.func1(0x23bbc58, 0xc01d66a6f0, 0x1e793a0, 0xc00aa703c0, 0x1eeac80, 0xc00a64db00, 0x23bbc58, 0xc01d66a6f0)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/x/staking/types/tx.pb.go:696 +0x89
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1(0x23bbc58, 0xc01d66a660, 0x1e793a0, 0xc00aa706c0, 0xc01445e220, 0xc01c5d7d58, 0xc00bc82278, 0x4c38e6, 0x1dcaa60, 0xc01d66a660)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/msg_service_router.go:113 +0x114
github.com/cosmos/cosmos-sdk/x/staking/types._Msg_Delegate_Handler(0x1ef8c40, 0xc000d91b80, 0x23bbc58, 0xc01d66a660, 0x21735f0, 0xc01445e200, 0x23bbc58, 0xc01d66a660, 0xc01d235f78, 0x0)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/x/staking/types/tx.pb.go:698 +0x150
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2(0x23bbbe8, 0xc000098010, 0x23d4e00, 0xc00aa70680, 0xb, 0x0, 0xc013bcf8c0, 0xe, 0x1966a, 0x28aa03cb, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/msg_service_router.go:117 +0x36d
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(0xc0001dc000, 0x23bbbe8, 0xc000098010, 0x23d4e00, 0xc00aa70680, 0xb, 0x0, 0xc013bcf8c0, 0xe, 0x1966a, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/baseapp.go:719 +0x2f5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc0001dc000, 0xc000f50802, 0xc000c97590, 0xe3, 0xf0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/baseapp.go:679 +0x4f7
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/test_helpers.go:22
github.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate(0x0, 0x0, 0x0, 0x23dfd10, 0xc00437c4a0, 0x0, 0x0, 0x23c5ac8, 0xc000f91290, 0x23d83d8, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/x/auth/tx/service.go:117 +0xbf
github.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler(0x1de11c0, 0xc0043d1ba0, 0x23bbc58, 0xc017122300, 0xc012c23680, 0x0, 0x23bbc58, 0xc017122300, 0x20, 0xc012206fe0)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/types/tx/service.pb.go:743 +0x214
github.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1(0x23bbbe8, 0xc000098010, 0x23d4e00, 0xc00aa70300, 0xb, 0x0, 0xc013bcf8c0, 0xe, 0x1966a, 0x28aa03cb, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/grpcrouter.go:93 +0x24a
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0xc0001dc000, 0xc004211340, 0xc00aa46000, 0xe6, 0x1e0, 0xc01669e930, 0x23, 0x1966a, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/abci.go:576 +0x1d5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc0001dc000, 0xc00aa46000, 0xe6, 0x1e0, 0xc01669e930, 0x23, 0x1966a, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/abci.go:420 +0x96f
github.com/tendermint/tendermint/abci/client.(*localClient).QuerySync(0xc000cfff20, 0xc00aa46000, 0xe6, 0x1e0, 0xc01669e930, 0x23, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/abci/client/local_client.go:258 +0x10c
github.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync(0xc001587400, 0xc00aa46000, 0xe6, 0x1e0, 0xc01669e930, 0x23, 0x0, 0x0, 0x203006, 0x203006, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/proxy/app_conn.go:159 +0x68
github.com/tendermint/tendermint/rpc/core.ABCIQuery(0xc01694d440, 0xc01669e930, 0x23, 0xc00aa46000, 0xe6, 0x1e0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/rpc/core/abci.go:20 +0xfc
reflect.Value.call(0x1cc0c40, 0x2175c10, 0x13, 0x1efd6da, 0x4, 0xc00a84bb80, 0x5, 0x5, 0xc00a84bb98, 0xc01bca1080, ...)
        /usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x1cc0c40, 0x2175c10, 0x13, 0xc00a84bb80, 0x5, 0x5, 0x1, 0x5, 0x0)
        /usr/local/go/src/reflect/value.go:337 +0xb9
github.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1(0x23b47a0, 0xc01c4e5b60, 0xc014a25a00)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/rpc/jsonrpc/server/http_json_handler.go:96 +0xc7e
github.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1(0x23b47a0, 0xc01c4e5b60, 0xc014a25a00)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/rpc/jsonrpc/server/http_json_handler.go:122 +0x9c
net/http.HandlerFunc.ServeHTTP(0xc00409d900, 0x23b47a0, 0xc01c4e5b60, 0xc014a25a00)
        /usr/local/go/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0xc004210f40, 0x23b47a0, 0xc01c4e5b60, 0xc014a25a00)
        /usr/local/go/src/net/http/server.go:2448 +0x1ad
github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP(0x237c180, 0xc004210f40, 0xf4240, 0x23b47a0, 0xc01c4e5b60, 0xc014a25a00)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/rpc/jsonrpc/server/http_server.go:236 +0xd9
github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1(0x23b4e30, 0xc00ad3a0e0, 0xc014a25a00)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/rpc/jsonrpc/server/http_server.go:209 +0x39a
net/http.HandlerFunc.ServeHTTP(0xc0034a6990, 0x23b4e30, 0xc00ad3a0e0, 0xc014a25a00)
        /usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc000c9d340, 0x23b4e30, 0xc00ad3a0e0, 0xc014a25a00)
        /usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00afd3040, 0x23bbc58, 0xc00a8fa3c0)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x39b
: panic: invalid request
`

----
## Additional investigation:
It was caused first time after I had been jailed and unjailed. I saw that my voting power became lower than before.

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by boostie** [comment]
To add to the original comment: sending the tokens from this address to a new address and delegating from there sends succeed, but after a certain time the new address may also face the same issue when delegating to a validator.

**Comment by alexanderbez** [comment]
Hey @boostie, thank you. But there's already an issue reported and created in the Cosmos SDK 👍
