### ISSUE TITLE
Liquidator must be incentivized to keep uTokens

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1158]
## Summary

In https://github.com/umee-network/umee/pull/1118 we allow liquidator to automatically receive the underlying token, instead of uToken.

The problem is that it removes the liquidity from the system, rather than incentivizing liquidator to keep the liquidity in the system

## Proposal

* Add one more global parameter to the system: `UTokenLiquidationFee`
* Whenever liquidator will decide to automatically redeem uToken to the underlying token when doing a liquidation, his premium will be reduced by `UTokenLiquidationFee`. Basically the premium he will receive will equal to `premium * (1-UTokenLiquidationFee)`

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by swisstackle** [comment]
Wouldn't you only want to charge a fee if the collateral utilization is at it's max though? Otherwise it will be harder to have liquidators' period - depending on how high the fee is.

Or maybe the higher the collateral utilization, the higher the fee?

**Comment by robert-zaremba** [comment]
In general we want to have an small incenitve to keep the liquidity in the protocol.

For this use case I think the simple solution will work, and we can consider more complex solutions in the future. Feel free to make a full proposal.
