### ISSUE TITLE
Readme.md doesn't tell users what to do

### ISSUE THREAD

**Issue by faddat** [umee-network/umee#116]
## Summary of Bug

Forget you know anything about blockchains and software, and read readme.md -- do you know wht to do?

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I don't follow, sorry @faddat. Can you describe the issue?
