### ISSUE TITLE
leverage: implement MaxCollateralShare restriction

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#1161]
`MsgCollateralize` should fail when the the collateralized denom would represent a greater share of the collateral market than its `MaxCollateralShare`.

Indirectly exceeding `MaxCollateralShare` will still be possible, for example if a collateral denomination's market share would increase due to a `MsgDecollateralize` of another collateral denomination, or secondary effects from liquidations or interest accruing.

**Comment by robert-zaremba** [comment]
`MsgBorrow` should fail as well.

**Comment by robert-zaremba** [comment]
Duplicate: https://github.com/umee-network/umee/issues/1093
