### ISSUE TITLE
leverage: implement MinCollateralLiquidity restriction

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#1163]
Any `MsgCollateralize`, `MsgWithdraw`, or `MsgBorrow` which would reduce `available supply / collateral` below a given value, should fail.

The limit can still be indirectly exceeded as an effect of `MsgLiquidate` or interest accruing on collateral.

**Comment by robert-zaremba** [comment]
related to: https://github.com/umee-network/umee/issues/1061
