### ISSUE TITLE
leverage: split available_borrow query into available_borrow, available_withdraw, and available_supply

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#1164]
Different messages are restricted or allowed by various market parameters or quanitities:

| Msg | MaxSupplyUtilization | MinCollateralLiquidity | Unreserved Module Balance |
| - | - | - | - |
| Borrow | x | x | x |
| Withdraw | | x | x |
| Liquidate |  |  | x |

That means each of those messages has a different amount of tokens "available" for use. A message restricted by multiple factors should return the lowest among them.

Propose splitting the current `available_borrow` into `available_borrow` (row 1), `available_withdraw` (row 2), and `available_supply` (row 3).

**Comment by toteki** [comment]
We'll probably need to figure out naming. However, implementation seems guaranteed to require 3 queries instead of the current 1.

**Comment by robert-zaremba** [comment]
I think it's better to have one query returning 3 values. User and UI will usually like to query all, so let's pack it into a single call.

**Comment by robert-zaremba** [comment]
However, we should rename. How about, `user_status`?

**Comment by toteki** [comment]
This query is about the market in general, and not any specific user. I will add the new fields to `market_summary` query, but would normally seek to create isolated queries as well.

**Comment by robert-zaremba** [comment]
Then let's don't add it unless someone needs it. Let's firstly verify if our UI app will benefit from it.
