### ISSUE TITLE
leverage: improve complete_liquidation_threshold

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#1166]
For `complete_liquidation_threshold = 0.15`

- Current implementation: `close_factor` reaches `1.0` when `borrowed_value / liquidation_threshold` reaches `1.15`

- Improved implementation: `close_factor` reaches `1.0` when `borrowed_value` is 15% of the way between liquidation threshold and collateral value, i.e when `borrowed_value = liquidation_threshold + 0.15 * (collateral_value - liquidation_threshold)`

Dynamic `close_factor` will still interpolate linearly between `close_factor = min_close_factor` at `borrowed_value = liquidation_threshold` and `close_factor = 1` at the point defined above.

**Comment by robert-zaremba** [comment]
I like the logic update, however we should use `>=` rather than `==`

Why 15%?

**Comment by toteki** [comment]
15% was just an example - I think our current default for that parameter is 10%

And yeah, it is `>=`
