### ISSUE TITLE
price-feeder: CI to check all the providers endpoints 

### ISSUE THREAD

**Issue by RafilxTenfen** [umee-network/umee#1182]
## Summary
- Implement a check on default providers endpoints to receive an alert if something external change 

## Problem Definition
- Right now we have default endpoints for our providers `["binance", "osmosis"...]`, but sometimes those providers deprecated our remove the endpoints

## Proposal
- We could have a check on that front to check if all the default endpoints are available
- Maybe it doesn't need to be on the GitHub actions kind of thing, accepting suggestions

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
I think the best would be to run a price feeder by ourselves, without pursing them to the blockchain. So the only thing the price feeder will do is logging errors.

**Comment by RafilxTenfen** [comment]
> I think the best would be to run a price feeder by ourselves, without pursing them to the blockchain. So the only thing the price feeder will do is logging errors.

Do you mean like a VM with price-feeder running all the time and sending notifications if some error happens?

**Comment by adamewozniak** [comment]
Setting low priority here - we generally end up seeing this on testnet anyways

**Comment by robert-zaremba** [comment]
Should be solved by our monitoring plan.

**Comment by zarazan** [comment]
Closing since we have added the price-feeder integration tests to CI https://github.com/ojo-network/price-feeder/tree/main/tests/integration
