### ISSUE TITLE
Price-feeder: symbol denom mapping

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#1183]
## Summary

Sometimes the symbol denom in our state machine might not be exactly the same as the coin we're trying to provide prices. When this happens, we currently need to do a gov proposal to fix it.

In order to keep this from happening, we should add the ability for validators to map price denoms -> voting denoms, e.g., "JUNO" -> "JUNOX". 

Note: This should _**not**_ be used with tokens that are actually different, such as wrapped eth vs eth. 

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
the more I think about this, the less I like it - we can’t really assume that it would only be used for testnet tokens like junox. It would more likely be incorrectly used for wrapped / similar but not the same assets. 

Closing this for now

**Comment by robert-zaremba** [comment]
Agree with your final comment @adamewozniak . It smells like a source of potential bugs.

BTW, when or why the denom mismatch happens? Is this due to validator missconfiguration?
