### ISSUE TITLE
Leverage: (HAL-08) PANIC IS USED FOR ERROR HANDLING

### ISSUE THREAD

**Issue by RafilxTenfen** [umee-network/umee#1196]
## Summary
Several instances of the panic function were identified in the codebase. They appear to be used to handle errors. This can cause potential issues, as invoking a panic can cause the program to halt execution and crash in some cases. This in turn can negatively impact the availability of the software for users

## Problem Definition
- https://github.com/umee-network/umee/blob/rafilx/umeed-cosmwasmd/x/leverage/abci.go#L11-21
- https://github.com/umee-network/umee/blob/rafilx/umeed-cosmwasmd/x/leverage/keeper/keeper.go#L64-66

## Proposal
Instead of using panics, custom errors should be defined and handled according to the [Cosmos best practices](https://docs.cosmos.network/main/building-modules/errors.html).
---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
All our instances of panic are
- Store unmarshal fail on getter ("should never happen" - similar to SDK's approach to `bank.GetBalance`)
- EndBlocker (which MUST halt the chain on error)
