### ISSUE TITLE
Leverage: (HAL-09) OPEN TODOs

### ISSUE THREAD

**Issue by RafilxTenfen** [umee-network/umee#1197]
## Summary
Open To-dos can point to architecture or programming issues that still need to be resolved. Often these kinds of comments indicate areas of complexity or confusion for developers. This provides value and insight to an attacker who aims to cause damage to the protocol.

## Problem Definition

Listing 18: Open Todos
1 ./x/ leverage / module .go :28: // TODO : Ensure x/ leverage implements simulator and then uncomment.
2 ./x/ leverage / keeper / interest .go :164: // TODO : use typed events
3 ./x/ leverage / keeper / interest .go :76: // @todo fix this when tender mint solves #8773

## Proposal
Consider resolving the To-dos before deploying code to a production context. Use an independent issue tracker or other project management software to track development tasks.

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
I'm really having an impression that more and more auditing companies are spending their time on linting the code rather than searching for vulnerabilities.

**Comment by adamewozniak** [comment]
See my comment here: 
https://github.com/umee-network/umee/pull/1231#issuecomment-1210795366
