### ISSUE TITLE
Genesis for functional tests

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1206]
Create a genesis file with accounts, leverage module setting and oracle setting we will use in the functional tests.
 
Let's store the first version of the genesis in https://github.com/umee-network/qa-integration.

Suggestion:
* in the genesis generate accounts: `a_1, ... , a_1000`
* each account will have 10'000atom, 20'000juno and 1'000'000umee

**Comment by robert-zaremba** [comment]
@toteki  , @adamewozniak  can you take a lead on generating some initial genesis parts for leverage and oracle respectively? Feel free to break this task if needed. @RafilxTenfen chat with Adam.M and Woz if they will need more hands.

**Comment by toteki** [comment]
Note: Since this is meant to not require ibc channels, we can probably use fake IBC denoms `ibc/ATOM`, `ibc/OSMO`, etc when adding tokens, balances, and metadata.

That way anyone who reads it is clear that both
- they're representing ibc denoms
- they're not real hashes

**Comment by robert-zaremba** [comment]
We don't even need to use IBC denoms.
