### ISSUE TITLE
Add parameters to leverage module

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#125]
## Summary

Some initial governance parameters should be added to the `umee/x/leverage` keeper to support borrowing, and future interest rate calculations and liquidation checks.

These parameters do not include values that come from price oracles.

They should roughly cover:
- Token whitelisting
- Required overcollateralization levels (set for each token)
- Base interest rate (set for each token; real interest rates are likely base+dynamic based on supply/demand later)

(Question: Is base interest rate per-token or global? Assumed to be per-token in the table below.)

## Proposal

The leverage keeper should store the following values _per whitelisted base asset type_.

| Value | Example | Used By | Updated When |
| - | - | - | - |
| name | `uatom` | all | On initial whitelist |
| uToken | `u/uatom` | all | On initial whitelist |
| uToken exchange rate | `1.112 uatom = 1 u/uatom` | Lend, Withdraw, Borrow, Repay | On initial whitelist (=1), EndBlock (increase only) |
| collateral weight | `0.67 actual u/uatom value counts towards borrow limit` | Borrow (determine borrowing limit), EndBlock (check if liquidate) | On initial whitelist, on governance action |
| base borrowing interest rate | `uatom borrow interest rate is 10% annually plus a dynamic amount based on demand` | EndBlock (calculate borrow interest) | On initial whitelist, on governance action |

Note: the first two parameters - token denom and associated uToken denom - already exist in the keeper because of lending feature.

Also, we might consider ways to store and interpret these parameters as integers to avoid floating point shenanigans (e.g. nondeterministic math at least significant bit based on CPU type)

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by brentxu** [comment]
>(Question: Is base interest rate per-token or global? Assumed to be per-token in the table below.)

Per token.
