### ISSUE TITLE
Price-feeder: Add named string for Asset

### ISSUE THREAD

**Issue by zarazan** [umee-network/umee#1256]
## Summary

For readability a named string could be added for using the AggregatedProviderCandles variable when specifying the name of an Asset.

https://github.com/umee-network/umee/pull/1255#issuecomment-1220963115

## Problem Definition

I would also want to give a name ( https://github.com/umee-network/umee/issues/1167 ) to the string key in maps like
AggregatedProviderCandles map[Name]map[string][]types.CandlePrice to -> AggregatedProviderCandles map[Name]map[Asset][]types.CandlePrice

https://github.com/umee-network/umee/blob/main/price-feeder/oracle/provider/provider.go#L62

## Proposal

The oracle name "Name" should probably be updated as well but it will require updating a decent amount of different files.

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
@zarazan would you like to create a draft PR?

**Comment by adamewozniak** [comment]
Setting this as low priority

**Comment by zarazan** [comment]
Closing this in favor of other larger refactors to how we store prices: https://github.com/ojo-network/price-feeder/issues/105
