### ISSUE TITLE
Price-feeder: additional apis

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#1263]
## Summary

In order to have some increased ease of debugging we should add some API endpoints to the price feeder. Logs & telemetry are nice but not as readable. We should have a couple new endpoints which show: 

* Provider -> calculated tvwap (candles) 
* Provider -> calculated vwap (tickers)

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
Thoughts on this @RafilxTenfen ? I know we have telemetry already but I think this will make price feeder easier to debug in production

**Comment by RafilxTenfen** [comment]
Agree, also would be nice to know the providers available and which currency pairs they are looking at the moment, I know we have that on the config, but it would make it easier to get data as well
