### ISSUE TITLE
CI fail -  liveness and unit-cover

### ISSUE THREAD

**Issue by RafilxTenfen** [umee-network/umee#1265]
## Summary
- Sometimes some CI checks fail and if you rerun it, it works, let's check what's up with that, maybe changing some parameters is enough

## Problem Definition
- Tests / liveness-test
- Tests / test-unit-cover

## Proposal

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RafilxTenfen** [comment]
see #1262 github actions=

**Comment by adamewozniak** [comment]
I think the liveness test fails because protobuff occasionally can't build (seems like a cli bug)

Ex. 

```
[STARPORT] cosmos/base/v1beta1/coin.proto:32:8: Option "(cosmos_proto.scalar)" unknown. Ensure that your proto definition file imports the proto which defines the option.
[STARPORT] cosmos/base/v1beta1/coin.proto:37:19: Option "(cosmos_proto.scalar)" unknown. Ensure that your proto definition file imports the proto which defines the option.
[STARPORT] cosmos/base/v1beta1/coin.proto:42:19: Option "(cosmos_proto.scalar)" unknown. Ensure that your proto definition file imports the proto which defines the option.
[STARPORT] umee/leverage/v1/genesis.proto:4:1: Import "cosmos/base/v1beta1/coin.proto" was not found or had errors.
[STARPORT] umee/leverage/v1/genesis.proto:18:12: "cosmos.base.v1beta1.Coin" is not defined.
[STARPORT] umee/leverage/v1/genesis.proto:25:12: "cosmos.base.v1beta1.Coin" is not defined.
[STARPORT] umee/leverage/v1/genesis.proto:35:3: "cosmos.base.v1beta1.DecCoin" is not defined.
[STARPORT] umee/leverage/v1/genesis.proto:42:3: "cosmos.base.v1beta1.Coin" is not defined.
[STARPORT] : exit status 1
```

Please lmk if you're experiencing the same thing

**Comment by robert-zaremba** [comment]
I haven't see it. But indeed, might be related to ignite CLI.

**Comment by robert-zaremba** [comment]
I propose to update the workflow to not use CLI. Instead, we can copy a config and genesis file into `contrib` directory.

**Comment by robert-zaremba** [comment]
solved by: https://github.com/umee-network/umee/pull/1306
