### ISSUE TITLE
Set price feeder config with mainnet options

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#1270]
## Summary

We’ll need to update the price feeder’s example config with the options necessary to run on mainnet. This will make it a bit easier for validators when we upgrade to V3

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
small task, merged by the end of the week.
