### ISSUE TITLE
Add migration script for IBC v2->v5

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1293]
## Summary

We are updating IBC from v2 (v1) -> v3.1 (current in v3-alpha) to v5-rc0. There are few migrations that need to happen.

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
Guide here: https://github.com/cosmos/ibc-go/releases/tag/v5.0.0-rc0

**Comment by robert-zaremba** [comment]
Mostly closed in https://github.com/umee-network/umee/issues/1293
The required ibc fees for anti spam will be done in a subsequent mainnet upgrade.
