### ISSUE TITLE
Add error check to in leverage simulations TestWeightedOperations

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1310]
## Summary

The `w.Op()(r, s.app.BaseApp, s.ctx, accs, "")` returns an error which is not checked.
https://github.com/umee-network/umee/blob/v3.0.0-alpha2/x/leverage/simulation/operations_test.go#L159

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
Added fix to #1300
