### ISSUE TITLE
Consider removing Amino support from x/leverage and x/oracle 

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1313]
## Summary
Amino is used only for legacy multisig, and has some bad artifacts left in tests. Now, that we have x/group module we should remove Amino support if possible

## Proposal
* remove `LegacyMsg` implementations
* remove `ModuleCdc = codec.NewAminoCodec(amino)` codecs we have for test purposes

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
Note: amino is also required for ledger support (message signing) and as a result, for our frontend's Kepler integration. We ran into this with `MsgMaxWithdraw` for which I did not add amino support initially.

Should we close this issue since amino support _should NOT_ be removed?

**Comment by robert-zaremba** [comment]
yes, let's close it. thanks for looking back to the issue.
