### ISSUE TITLE
Remove not required invariants in x/leverage endblocker

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1324]
## Summary

Nice to have for v3, otherwise we move it to v4.

Don't use compute intensive invariants in endblocker

## Problem Definition

Endblocker operations should be strictly minimum. Only required operations should happen there:
* no-one is paying for that operations
* all possible verification should happen at the tx level
* too time intensive operations can be dangerous for consensus (if operation will stuck somewhere or will impact the block time).
* finally they can cause chain halt.

https://github.com/umee-network/umee/pull/1300 added more invariants and we should rethink them.

## Proposal

* Use only strictly required invariants in the endblocker
* other invariants should be only applied for genesis load.

---

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by toteki** [comment]
We should specifically remove the "iterate all balances" invariants, but there's no scaling problem with the "iterate all denoms" ones.
