### ISSUE TITLE
Price-feeder improve metrics 

### ISSUE THREAD

**Issue by RafilxTenfen** [umee-network/umee#1373]
## Summary

- Change reconnect metric to have the provider as a parameter, so instead of 
   - `price_feeder_websocket_reconnect_provider_coibase`
   - `price_feeder_websocket_reconnect_provider_gate`
   - `price_feeder_websocket_reconnect_provider_okx` 
We should have `price_feeder_websocket_reconnect{provider="gate"}`

## Proposal

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RafilxTenfen** [comment]
@adamewozniak let me know what do you think about this ^^

**Comment by RafilxTenfen** [comment]
@julio-jimenez what were the other metrics to do this?

**Comment by julio-jimenez** [comment]
```
price_feeder_websocket_message_type_candle_provider_x
price_feeder_websocket_message_type_ticker_provider_x
price_feeder_websocket_message_type_trade_provider_x
```
We could merge these three and have only 
```
price_feeder_websocket_message{type="x", provider="x"}
```

Also
```
price_feeder_failure_provider_candle
price_feeder_failure_provider_type_ticker
```
=>
```
price_feeder_failure_provider{type="x", provider="x"}
```
And
```
price_feeder_websocket_subscribe_currency_pairs_provider_x
``` 
=> 
```
price_feeder_websocket_subscribe_currency_pairs{provider="x"}
```
