### ISSUE TITLE
x/leverage: Reconcile Params

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#144]
## Summary

Currently, the `x/leverage` module has the following parameters per token in its registry:

- base_denom
- exchange_rate
- collateral_weight
- base_borrow_rate

Compound has the following per token in their governance model:

- Collateral Factor, e.g. 0%
- Reserve Factor, e.g. 25%
- COMP Speed, e.g. 0.0014625
- APY borrow base rate, e.g. 2% 
- APY borrow rate at kink, e.g. 20%
- Kink at 80% utilization
- 100% APY borrow rate at 100% utilization

We need to reconcile what parameters we're missing and if we need them. Based on the above list, they seem to be:

- Reserve Factor, e.g. 25%
- COMP Speed, e.g. 0.0014625
- kink and utilization related fields

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
With the exception of COMP speed, which seems to relate to liquidity mining rather than any of our core features, all parameters mentioned will be completed when PR #179 merges.
