### ISSUE TITLE
Price-feeder: Websocket error handling improvements

### ISSUE THREAD

**Issue by zarazan** [umee-network/umee#1476]
## Summary

Price-feeder panics when hitting a websocket error

## Problem Definition

When one of the providers websockets fails it appears that we continue to try and read data from the websocket. This causes the entire price-feeder to panic.

## Proposal

We need to gracefully handle the websocket errors. Don't attempt to read data from it once the error has occurred and probably handle reconnecting with an exponential back-off

Error message:

`Oct 05 22:05:44 ns5010007 peggo[3332639]: 10:05PM ERR mexc: could not read message error="websocket: close 1006 (abnormal closure): unexpected EOF" provider=mexc
Oct 05 22:05:45 ns5010007 peggo[3332639]: 10:05PM WRN provider deviating from other candles base=ETH module=oracle price=1349.002296259336808127 provider=binance
Oct 05 22:05:45 ns5010007 peggo[3332639]: 10:05PM ERR mexc: could not read message error="websocket: close 1006 (abnormal closure): unexpected EOF" provider=mexc
Oct 05 22:05:45 ns5010007 peggo[3332639]: panic: repeated read on failed websocket connection
Oct 05 22:05:45 ns5010007 peggo[3332639]: goroutine 123 [running]:
Oct 05 22:05:45 ns5010007 peggo[3332639]: github.com/gorilla/websocket.(*Conn).NextReader(0xc001c44420)
Oct 05 22:05:45 ns5010007 peggo[3332639]:         /home/umee/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1030 +0x27f
Oct 05 22:05:45 ns5010007 peggo[3332639]: github.com/gorilla/websocket.(*Conn).ReadMessage(0xc001b2ef70?)
Oct 05 22:05:45 ns5010007 peggo[3332639]:         /home/umee/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1093 +0x19
Oct 05 22:05:45 ns5010007 peggo[3332639]: github.com/umee-network/umee/price-feeder/oracle/provider.(*MexcProvider).handleWebSocketMsgs(0xc00147f4a0, {0x2736b30, 0xc000f88880})
Oct 05 22:05:45 ns5010007 peggo[3332639]:         /home/umee/go/pkg/mod/github.com/umee-network/umee/price-feeder@v1.0.1-0.20220919160536-0c0db8c7c112/oracle/provider/mexc.go:349 +0x13e
Oct 05 22:05:45 ns5010007 peggo[3332639]: created by github.com/umee-network/umee/price-feeder/oracle/provider.NewMexcProvider
Oct 05 22:05:45 ns5010007 peggo[3332639]:         /home/umee/go/pkg/mod/github.com/umee-network/umee/price-feeder@v1.0.1-0.20220919160536-0c0db8c7c112/oracle/provider/mexc.go:126 +0x7c5
Oct 05 22:05:45 ns5010007 systemd[1]: peggod.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 05 22:05:45 ns5010007 systemd[1]: peggod.service: Failed with result 'exit-code'.
Oct 05 22:05:55 ns5010007 systemd[1]: peggod.service: Scheduled restart job, restart counter is at 1.
Oct 05 22:05:55 ns5010007 systemd[1]: Stopped Peggo Service.`

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zarazan** [comment]
The documentation for the websocket library we use recommends `Applications must break out of the application's read loop when this method returns a non-nil error value. Errors returned from this method are permanent. Once this method returns a non-nil error, all subsequent calls to this method return the same error.` This appears to be the opposite of how we currently handle it: https://github.com/umee-network/umee/blob/main/price-feeder/oracle/provider/mexc.go#L351.

I propose we check for if it is a close error `if websocket.IsCloseError(err)` and go through some standard reconnecting process before we start reading from the websocket again.

However the logic for connecting/reconnecting is duplicated for every provider, I also suggest refactor this code into a single `WebsocketHandler` that handles this logic for all the providers using websockets.

@adamewozniak @RafilxTenfen @rbajollari

**Comment by RafilxTenfen** [comment]
@zarazan Sounds great!
