### ISSUE TITLE
style: enable certain revive linter rules

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#1536]
PR #1535 introduced a specific list of rules to run for the revive linter.

To maintain PR scope, some of the rules listed in `.golangci.yml` and `.revive.toml` are commented out due to active errors. They should be re-enabled and fixed.

Note: I also noticed some `gofumpt` formatting diffs that will occur on `make lint`

**Comment by robert-zaremba** [comment]
@toteki , Which rules, in your opinion, we should re-enable?
This will be a good task for new team member.

**Comment by toteki** [comment]
Ah - too late. I fixed this in #1649
