### ISSUE TITLE
temporarily disable historacle params

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#1585]
Merging the historacle params into `proto` definitions early has caused a few problems:
- `main` branch is incompatible with `umee-1` mainnet genesis state (`panic: cannot unmarshal empty bytes` on start)
- a premature migration is being proposed for release `3.2` to address a feature (historacle) which is still being drafted

The new params should be disabled in `main` branch, especially during release to avoid unnecessary problems, and re-enabled later.

**Comment by robert-zaremba** [comment]
Let's close this. It will be solved by https://github.com/umee-network/umee/issues/1668 and https://github.com/umee-network/umee/pull/1656
