### ISSUE TITLE
Goreleaser not working properly

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#1591]
## Summary of Bug

The price feeder goreleaser is not working right now, we need to fix it for PFv2 RCs 

Example: https://github.com/umee-network/umee/actions/runs/3465860390/jobs/5789084144

I have a temp fix for this in #1594 for the price feeder, but this will need to be addressed for the `umeed` binary as well I believe. Adding sai on this task to check out when he can 🙏 

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
Price Feeder shouldn't depend on wasm. 
Maybe there is a way to remove that dependency... somehow instrumenting the go builder to only include what is needed.

**Comment by robert-zaremba** [comment]
I think the problem comes through the simulation package - which is included in Oracle without a test build.
So one way to solve it is to rafactore the simulation package.

**Comment by robert-zaremba** [comment]
So, to avoid a bloated binary, we should work on dependencies anyway, and make sure we limit what we can limit.

**Comment by robert-zaremba** [comment]
@adamewozniak , @zarazan let's rename this task to:
* refactor oracle module to make the `types` not depend on the core nor cosmwasm. This way we can import oracle/types without pulling other, not necessary dependencies.

Otherwise the rest of the problems were moved and solved in https://github.com/umee-network/umee/pull/1606

**Comment by adamewozniak** [comment]
> @adamewozniak , @zarazan let's rename this task to:
> 
> * refactor oracle module to make the `types` not depend on the core nor cosmwasm. This way we can import oracle/types without pulling other, not necessary dependencies.
> 
> Otherwise the rest of the problems were moved and solved in #1606

Please check this out when you get the chance @zarazan ❤️

**Comment by robert-zaremba** [comment]
Fixed it in #1606
