### ISSUE TITLE
Module migrations

### ISSUE THREAD

**Issue by gsk967** [umee-network/umee#1668]
## Summary of Bug

Currently we are not maintaining the migrations structure

- x/MODULE  
   - migrations  Ex: https://github.com/cosmos/cosmos-sdk/tree/main/x/staking/migrations
       - v1 (v1 migrations)  Ex: https://github.com/cosmos/cosmos-sdk/tree/main/x/staking/migrations/v1
       - v3 (v3 migrations)   Ex: https://github.com/cosmos/cosmos-sdk/tree/main/x/staking/migrations/v3
   - keeper
       - migrations.go ( add the respective migrations based on consensus version) Ex: https://github.com/cosmos/cosmos-sdk/blob/main/x/staking/keeper/migrations.go

# Module migrations  
- [ ] We need to refactor the oracle module migrations (https://github.com/umee-network/umee/pull/1632/files#diff-50d4e55bce30a44e1f591b1d795cc4b2129d4d339ed9e3940c9967703e756704L20)
> Here it is replacing the old migration with new changes but we need keep the old version migrations and create the new version migrations otherwise it will break version to version migrations 

## Version

Please provide the output of the following commands:

- Do migration from v3.2 to v3.3.0-rc2 

## Steps to Reproduce

1. Clone the repository , checkout to v3.2.0 tag then run the chain 
2. Upgrade the chain from v3.2.0 to v3.3.0-rc2 

----

## For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
The migration is in a wrong place. We don't change the consensus version. It's basically params update, which could be done as a traditional `param-change` proposal. That's why, IMO, we should do it without consensus update, and simply store it in the upgrades. I've already commented about it, and it seams it was not resolved :(
I will prepare a PR to clean it up.

**Comment by robert-zaremba** [comment]
Oh, in fact there is already another PR: #1656
And I've already commented there to move that function: https://github.com/umee-network/umee/pull/1656#pullrequestreview-1218175261
