### ISSUE TITLE
Speed up docker builds

### ISSUE THREAD

**Issue by zarazan** [umee-network/umee#1697]
## Summary

Both of the Umee docker file re-download all the go libraries every time any files are updated because all the files are copied over first before go mod download is ran. We should copy just the go.mod and go.sum files over first, run go mod download, and then copy over the rest of the application so when the image is rebuilt after some of the application files are changed it skips the very long process of downloading all the go libraries again unless the go.mod file has changed.

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zarazan** [comment]
@robert-zaremba This need to be done for the go.mod from the price feeder as well. Or we can wait until Ojo is ready and the pull out the price feeder anyways.

**Comment by robert-zaremba** [comment]
I've updated the `contrib/images/price-feeder.dockerfile`. Is tthere anything else missing @zarazan ?

**Comment by zarazan** [comment]
The docker build will still install a bunch of go packages after making non-package related changes. I'll try to diagnose it sometime soon. The goal is to reduce the time it takes to rerun the tests locally after making changes.

**Comment by robert-zaremba** [comment]
What kind of changes? We are copying the whole directory. So if you change any file in that directory it will force rebuild and every step after `COPY . .`

**Comment by robert-zaremba** [comment]
I don't think there is a clear way to optimize that. You would need to manually list all go files we want to copy. And that will be in multiple steps to preserve the the directory structure.

**Comment by zarazan** [comment]
My assumption is that there is still stuff we can move before the COPY . . command. I'll play around with it when I get some free time soon.
