### ISSUE TITLE
Leverage module API requests with arguments issue

### ISSUE THREAD

**Issue by shurinov** [umee-network/umee#1964]
## Summary of Bug

Leverage module API requests don't accept requests with parameters, for example:

```
$curl localhost:1317/umee/leverage/v1/account_balances/umee1r0j7argxpvhdym5a3qgqc7a6acjetwhvx5w
{
  "code": 12,
  "message": "Not Implemented",
  "details": [
  ]

```

## Version

$ umeed version
HEAD-079f7d6a81624eb7486c7474967927ab6c283a56
(tag v4.2.0) 

$ go version
go version go1.19 linux/amd64

$ uname -a
Linux ovh-adv3 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

## Steps to Reproduce

1. run node with enabled leverage module by ``` umeed start -l```
2. make sure that API enabled (config/app.toml)
3. Wait node syncronization
4. Try to request API commands with arguments, like  /umee/leverage/v1/market_summary/, /umee/leverage/v1/account_balances/ etc
 

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
If you need to work with the current endpoints, they resemble
`.../umee/leverage/v1/account_summary?address=umee1s84d29zk3k20xk9f0hvczkax90l9t94g72n6wm`

But we'll have a look at the PR as well
