### ISSUE TITLE
x/oracle: evaluate ApplyWhitelist metadata

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#225]
In `Keeper#ApplyWhitelist` of the `x/oracle` module, we update ToBin tax info and
we also apply updates to `x/bank` metadata. We need to evaluate if the metadata
we're provided is correct.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
Pretty sure this was closed with #296, where we decided to remove this altogether

**Comment by alexanderbez** [comment]
Yup, that's right @adamewozniak -- thank you 🙏
