### ISSUE TITLE
x/peggy: increase CLI test coverage

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#227]
## Summary

Increase CLI test coverage of `x/peggy` by testing all the (currently untested) CLI command handlers.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by facundomedica** [comment]
Closing as we are not using Peggy anymore
