### ISSUE TITLE
x/peggy: increase msg server test coverage

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#228]
## Summary

Increase message server test coverage of `x/peggy` by testing all the (currently untested) message handlers.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by facundomedica** [comment]
Closing as we are not using Peggy anymore
