### ISSUE TITLE
Offchain liquidation tool

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#229]
## Summary

Need offchain tool (liquidator bot) to detect and potentially act on liquidation opportunities.

## Problem Definition

The `x/leverage` module will provide queries by which users can look for borrowers who are over their borrow limits, and send `MsgLiquidate` messages to liquidate their borrow positions.

A tool should be created which allows a liquidator to automate the process of querying for over-limit borrowers, evaluating their positions, and attempting a liquidation if the borrow meets certain criteria.

## Proposal

A liquidator bot should be created, which is meant to run alongside a node to quickly (and without burdening the network) identify and liquidate over-limit borrow positions.

The bot will query the node and send `MsgLiquidate` messages on certain conditions. Specific features and technical requirements should be determined after we have done more work on the CLI and gRPC endpoints.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
@toteki can you by chance posture what queries we'd possibly need? i.e. what data will be relevant and necessary to this tool? Answering that will help you get started on the gRPC service.

**Comment by toteki** [comment]
From what I can see, the process in terms of keeper logic is roughly this:

```
Iterate through a list of all open borrows (stored as: prefix | borrowerAddr | denom => amount `sdk.Int`)
- Group all denoms borrowed by each borrower address (map borrowerAddr => total `sdk.Coins`)

Then, for each borrower address
- Get borrower's uToken balance
- Get borrower's collateral settings
- Use Oracle + Collateral Settings + uToken balance to compute borrow limit
- Use Oracle + Open Borrows to compute total borrowed value
- If over borrow limit, use necessary params to compute potential liquidation profit (depends also on what collateral denom is to be liquidated)
- If acceptable, send a `MsgLiquidate` to attempt the action.
```

There are two basic approaches to dividing up this labor between the tool and the keeper.

Approach 1: Favors serving huge amounts of data without much node-side computation
```
gRPC service exposes the following
- Get all borrows (for all borrower addresses)
- Get token balances (for one, or all, borrowers. Used for uTokens)
- Get collateral settings (for one, or all, borrower addresses)
- Get params
- Get token (for token params, like liquidation incentives)

The bot would then carry out the computations and identify borrowers over limit.
```

Approach 2: Relies on more computation in keeper functions, but reduces data served
```
gRPC service exposes the following
- List borrower addresses which are over their borrow limit 
- Get borrows (for one borrower)
- Get collateral balance (for one borrower)
- Get params
- Get token (for token params, like liquidation incentives)

The bot uses the initial list of liquidation targets, to evaluate each one against its own preferences and potentially act.
```

I assume it will become increasingly impractical to use something like approach 1 as the number of borrowers goes up.

**Comment by toteki** [comment]
There might be some miscellaneous things to add too, such as a "get current block height" which allows to tool to recognize when it's already done its current iteration and should wait for the next block.

**Comment by toteki** [comment]
I'll propose a brief part of this as a section in the liquidation ADR.

It will probably be an improved version of approach 2, but with less redundant fetching of data (e.g. collateral and borrow balance) that was already used to compute the list of borrowers over limit.

**Comment by alexanderbez** [comment]
Approach 2 makes sense. We need to strive to reduce the data transferred over gRPC responses as that has actually been shown to cause nodes to halt/crash.

Also, there is already an endpoint for getting the current block height.

**Comment by alexanderbez** [comment]
The current proposal to provide a grant to the community to implement this tool.

**Comment by alexanderbez** [comment]
Being tracked and developed in the liquidator repo.

**Comment by adamewozniak** [comment]
@toteki I don't believe this is still a requirement for mainnet - should we remove it from the [calypso milestone](https://github.com/umee-network/umee/milestone/5)? And maybe close this in favor of tracking in an issue in that repo

**Comment by toteki** [comment]
Yeah, we can move any issue tracking over there.
