### ISSUE TITLE
x/peggy: Valset reward requires the base ERC20 to be created beforehand

### ISSUE THREAD

**Issue by facundomedica** [umee-network/umee#244]
## Summary of Bug

Currently, when setting a valset reward, the chain will fail to initialize due to a check of the valset reward's denomination not being deployed as an ERC20 token. Needless to say that this is impossible given that ERC20s are deployed on Ethereum and then picked up by the Cosmos node using events from the orchestrator.

```
ERR CONSENSUS FAILURE!!! err="Invalid Valset reward! Correct or remove the paramater value" module=consensus
```

This error is thrown in `RewardToERC20Lookup` (https://github.com/umee-network/umee/blob/main/x/peggy/keeper/cosmos_originated.go#L73):

```go
// RewardToERC20Lookup is a specialized function wrapping DenomToERC20Lookup designed to validate
// the validator set reward any time we generate a validator set
func (k *Keeper) RewardToERC20Lookup(ctx sdk.Context, coin sdk.Coin) (common.Address, sdk.Int) {
	if len(coin.Denom) == 0 || coin.Amount.BigInt() == nil || coin.Amount == sdk.NewInt(0) {
		panic("Bad validator set relaying reward!")
	} else {
		// reward case, pass to DenomToERC20Lookup
		_, addressStr, err := k.DenomToERC20Lookup(ctx, coin.Denom)
		if err != nil {
			// This can only ever happen if governance sets a value for the reward
			// which is not a valid ERC20 that as been bridged before (either from or to Cosmos)
			// We'll classify that as operator error and just panic
			panic("Invalid Valset reward! Correct or remove the paramater value")
		}
		err = types.ValidateEthAddress(addressStr.Hex())
		if err != nil {
			panic("Invalid Valset reward! Correct or remove the paramater value")
		}
		return addressStr, coin.Amount
	}
}
```

after being called by `GetCurrentValset` (`https://github.com/umee-network/umee/blob/main/x/peggy/keeper/keeper.go#L479`)
```go
func (k *Keeper) GetCurrentValset(ctx sdk.Context) *types.Valset {
/// some lines skipped for brevity
	// get the reward from the params store
	reward := k.GetParams(ctx).ValsetReward
	var rewardToken common.Address
	var rewardAmount sdk.Int
	if reward.Denom == "" {
		// the case where a validator has 'no reward'. The 'no reward' value is interpreted as having a zero
		// address for the ERC20 token and a zero value for the reward amount. Since we store a coin with the
		// params, a coin with a blank denom and/or zero amount is interpreted in this way.
		rewardToken = common.Address{0x0000000000000000000000000000000000000000}
		rewardAmount = sdk.NewIntFromUint64(0)

	} else {
		rewardToken, rewardAmount = k.RewardToERC20Lookup(ctx, reward) // <--- HERE
	}
	// TODO: make the nonce an incrementing one (i.e. fetch last nonce from state, increment, set here)
	return types.NewValset(uint64(ctx.BlockHeight()), uint64(ctx.BlockHeight()), bridgeValidators, rewardAmount, rewardToken)
}
```

## Possible solution

- Ditch `RewardToERC20Lookup` and just use `DenomToERC20Lookup`.
- If the returned address is the zero address then the reward amount is going to be 0.
- Valset updates won't give out any rewards until the selected denom has been deployed on Peggy.
- **Do not panic**

## Follow-up questions/issues/conclusions

- Is it possible to change these values after the chain has started?
- Should we try to make this a profitable action by validators? Sounds incredibly difficult, Cosmos doesn't know how much an updateValset tx will cost.

In terms of incentive, there's some degree of "indirect incentive". Relaying valsets is in best interest of the validators, because if they don't do it the bridge will eventually halt and they won't be able to profit anymore from batches. No need to mention that if the bridge halts their staked tokens' price will probably decrease as this would be a negative event.

On the other hand, it would be very easy to subsidize this txs.
1. Pick the top 2 or 3 validators
1. Ask them to enable valset update relaying
1. Pay them the `(gascost - rewards)`

**Something to be clear about is that these rewards are basically minted out of thin air, so we have to be very careful as this will increase the circulating supply.**

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I think we should chat with Injective folks -- they can help describe this part better to us. In fact, I'm curious if we even want to support this functionality? Rather, is the complexity worth it? Between the various rewards from Umee and the orchestrator fees, I'm leaning towards holding off/disabling this for now. Although, it's great to document this for future feature completeness. WDYT?

**Comment by facundomedica** [comment]
What happens on this one is more or less the same "issue" we encountered at the beginning, Injective seems to be using a token that is deployed before the chain started and not one that got deployed using the `deployERC20` function from Peggy. If we enable this somehow once the chain was started, it shouldn't be an issue, because the ERC20 will be already registered.

I don't think it's really necessary to have it implemented, because of the "indirect incentive" validators have to relay them. Also, as long as 1 validator relays them, we are good.

I was going to give this a quick check and ended up going down the rabbit hole 🤣

**Comment by facundomedica** [comment]
Closing as we are not using Peggy anymore
