### ISSUE TITLE
x/peggy: Reject TXs going to invalid addresses

### ISSUE THREAD

**Issue by facundomedica** [umee-network/umee#247]
Adding invalid TXs will create a loop of failing batches until the tx times out. It's a very cheap way to halt the bridge.

In this example I sent some uumee to `0x0000000000000000000000000000000000000000`

```
1:33PM ERR failed to estimate gas cost error="execution reverted: ERC20: transfer to the zero address" module=peggy_relayer
1:33PM ERR failed to relay tx batches; retrying... error="execution reverted: ERC20: transfer to the zero address" loop=RelayerMainLoop module=peggy_relayer retry=9
```

Ref: https://github.com/umee-network/peggo/issues/69

## Possible solution

Reject any new transaction going to this address.

## Future issues

It's very unlikely, but if there's an ERC20 that reverts transactions going to a specific address, then we'll have the same issue.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
@facundomedica where do you think the fix belongs? Should `ValidBasic` fail on the SendToEth message type? Or should we have the check in the message handler?

Re future concerns, I'm not sure there's much we can do about that?

**Comment by facundomedica** [comment]
@alexanderbez I'm not sure what would be the difference between both. If I understand correctly,`ValidateBasic` happens only when sending the message on the client side. So in that case I would like to check for this in the message handler so even a misconfigured node/client can't create these txs. Again, I'm not sure if this is how it works 😅 

About future concerns, yeah, we shouldn't worry about that. If a widely used token has some specific revert cases, we'll have to do an update of the Peggy module adding hardcoded cases.
I'm trying to find USDT's contract, because they have a blacklist and I would like to know if they revert transactions going to those addresses

**Comment by alexanderbez** [comment]
Ok, I'll update the message handler 👍
