### ISSUE TITLE
x/leverage: Improve events and logs from RepayAsset and Liquidate

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#257]
## Summary

Improve logs and events emitted by functions in `x/leverage/keeper/msg_server.go`

## Problem Definition

1. Borrower repayment amount can be less than the `MsgRepay.Amount` if the submitted amount is greater than the total borrowed. (The transaction succeeds without overpaying.) Logs and events should reflect the amount actually repaid, not the larger amount attempted.
2. Liquidations also produce information not contained within `MsgLiquidate`. Namely, the reward amount (which is determined by exchange rates at the time of the transaction) is not in the original message but should be logged.

## Proposal

Additional return values can be added to `keeper.RepayAsset` and `keeper.Liquidate` which provide the desired information. They can then be used inside `msg_server.go` when composing the relevant events and logs.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
ACK. Thanks @toteki!
