### ISSUE TITLE
x/oracle: increase test coverage for msg server & grpc querier 

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#265]
## Summary

Need to add testing for the x/oracle's msg server / grpc querier

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Thanks @adamewozniak! You mean the gRPC querier, right?

**Comment by adamewozniak** [comment]
> Thanks @adamewozniak! You mean the gRPC querier, right?

Yup!
