### ISSUE TITLE
x/leverage: Choose default params

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#276]
## Summary

Default params are ready to be chosen in `x/leverage/types/params.go`

## Problem Definition

`DefaultInterestEpoch` The number of blocks (e.g. `100`) between interest calculations.

`DefaultCompleteLiquidationThreshold` How far over borrow limit (e.g. `0.1` = 10% over limit) a borrower must be to be liquidated fully in a single transaction).

`DefaultMinimumCloseFactor` The portion of a borrower's borrowed value (e.g. `0.01` = 1% borrow value) that can be liquidated in a single transaction, when the borrower is just over their borrow limit)

`DefaultOracleRewardFactor` The portion of accrued interest (e.g. `0.01` = 1%) on all borrows that funds the `x/oracle` reward pool.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
DefaultOracleRewardFactor added to issue description

**Comment by alexanderbez** [comment]
@toteki I would just your discretion here to set default values and then close this issue.

The values we decide to use in genesis for mainnet we'll discuss internally 👍
