### ISSUE TITLE
x/leverage: Prevent collateral uToken transfer

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#286]
## Summary

If borrowers who are using uTokens as collateral are able to send those uTokens to another address, then they can steal unlimited assets from the system by borrowing assets with one account then sending their uToken collateral to another account they control, repeating the process with new accounts as necessary.

## Proposal

We should either prevent uToken transfers under _any_ circumstances, or selectively block uToken transfers from accounts when the uToken denomination in question has been enabled as collateral.

If neither of the above is possible with the sdk, then we would have to store all uToken balances in the `x/leverage` keeper, similar to how borrowed amounts are stored, rather than actually minting and sending uTokens. (The math/economics of the system would be unchanged.)

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
@toteki I was under the impression that when you loan an asset and receive uTokens in response, you can then use those uTokens as collateral to borrow another or same asset and _that the uTokens would then be sent to a module account._ 

How is it that you're able to use uTokens as collateral and still have them in your account? Do we not send them to a module account?

**Comment by toteki** [comment]
Right now uTokens remain in the borrower's account and are simply enabled/disabled as collateral. I had TODOs to prevent borrowers withdrawing or disabling collateral when that would reduce a borrower's borrow limit below their currently borrowed value, _but had somehow overlooked their basic ability to just transfer the uTokens regularly._

We could make it such that `MsgSetCollateral` moves uTokens into the module account (and records the amount held for each user) when enabling collateral. `MsgSetCollateral` with `enable=false` would to the reverse.

Then `MsgLendAsset` and `MsgWithdrawAsset` could be adjusted to look for / create uTokens in the right place.

**Comment by toteki** [comment]
Since the module account doesn't currently hold uTokens for any other reason, there would be no problem using it for this purpose.

I'll start drafting a PR to make the necessary changes, and update `ADR-003-borrow-assets` (which also covers collateral settings) to reflect our intent.

**Comment by alexanderbez** [comment]
So moving them to a module account during `MsgSetCollateral` seems like it would work. However, can't we also just move the tokens to a module account when they borrow?

**Comment by toteki** [comment]
Assuming we transfer 100% of a borrower's enabled collateral to module at the moment of borrow, we would still have to correctly respond to the borrower enabling or disabling denominations as collateral after the fact, which would result in doing the same thing with `MsgSetCollateral`.

It's also not feasible to transfer less than 100% of enabled collateral at the moment of borrowing (like only transferring enough to cover their borrow) due to price fluctuations and some other complexity that would result.

**Comment by alexanderbez** [comment]
Makes sense. Let's go with the `MsgSetCollateral` approach then. Modifying `x/bank` is not worth the complexity IMO.
