### ISSUE TITLE
x/oracle: exchange rate issues

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#305]
A few issues I found with testing out the price-feeder and x/oracle module:

1. The exchange rates in state, specifically the denom, does not look correct:

```
      "exchange_rates": [
        {
          "denom": "ATOM\u0000",
          "exchange_rate": "22.759866700267157206"
        }
      ],
```

2. Querying for all exchange rates results in a panic:

```
$ umeed q oracle exchange-rates
Error: rpc error: code = Unknown desc = panic message redacted to hide potentially sensitive system info: panic
Usage:
```

3. Querying exchange rate for a specific denom fails:

```
$ umeed q oracle exchange-rate atom
Error: rpc error: code = InvalidArgument desc = atom: unknown denom: invalid request
```

These are all probably related somehow...

I used the following price-feeder config (change addresses as needed): https://pastebin.com/PxekXX6w

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
Note - #300 solves some of this (to make the tests pass), specifically running `umeed q oracle exchange-rates`, the rest will be addressed in a separate PR

**Comment by alexanderbez** [comment]
> Note - #300 solves some of this (to make the tests pass), specifically running `umeed q oracle exchange-rates`, the rest will be addressed in a separate PR

ACK, thanks for confirming @adamewozniak

**Comment by adamewozniak** [comment]
#300 now solves 1, 2, and 3 - although, I've found a problem where the exchange rates are periodically lost, which causes 
`umeed query oracle exchange-rates` to return `exchange_rates: []`, and `umeed query oracle exchange-rate ATOM` to panic.

Also, if the capitalization of a specific exchange rate is off ( e.g. `atom` instead of `ATOM`), specific exchange rates panic as well. We should address these before closing out this issue 👍

**Comment by alexanderbez** [comment]
So TODO:

- [ ] Normalize input when querying exchange rates by denom

>  I've found a problem where the exchange rates are periodically lost, which causes
umeed query oracle exchange-rates to return exchange_rates: [], and umeed query oracle exchange-rate ATOM to panic.

- We shouldn't probably say lost here. They'd have to be removed. You mean exchange rates are removed at the end of each voting period? Regardless, such a bug shouldn't cause a panic so we should at the very least make the query handler more robust.

**Comment by toteki** [comment]
If for any reason the exchange rate for an accepted `Token` does not exist or is set to zero during normal operations, lethal problems would occur (such as instant liquidation without compensation).

What are the exact symptoms we're dealing with, and is there any way to store the "most recent value" for rates in case the current one is zero / does not exist?

**Comment by alexanderbez** [comment]
Yeah I'm not quite following. I don't see why an exchange rate would "periodically" get lost. Can you point us to where this happens @adamewozniak?

**Comment by adamewozniak** [comment]
Looks like this was due to the time between ticks of the price feeder being too long (thank you @alexanderbez for the suggestion), PRing a fix for that problem shortly
