### ISSUE TITLE
x/leverage: ensure safety against empty exchange rates

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#329]
Currently, there is no direct positive incentive for validators to submit exchange rates to the oracle module (AFAIK -- correct me if I'm wrong @adamewozniak).

However, there is a direct negative incentive to not run one, which is validators will get slashed if they do not submit votes via `SlashAndResetMissCounters`. So we should technically never be in a situation where we have missing exchange rates for x/leverage registered assets.

However, I just want to be sure that we're safe against the case where exchange rates may be zero or missing. So any message execution should fail when the exchange rate is zero or missing.

In the case of Begin/EndBlock logic, we might screwed? Can you confirm @toteki ?

**Comment by toteki** [comment]
I'm thinking of putting extra lines of defense on `GetPrice`:

- Recover panics from oracle and turn them into an error (also helps with the bug I'm on)
- Add an error if an exchange rate is ever zero or nil

A second helpful fact: I think `GetPrice` is called during message-based transactions, but never automatically (like on an epoch or during begin/endblock). I'll have to confirm that.

If that's the case, then empty or zero exchange rates will cause transactions which rely on exchange rates to error, but will not halt the chain, and operations can resume normally once exchange rates exist. That will also prevent instant liquidation or other serious problems when an exchange rate is zero.

**Comment by toteki** [comment]
Also, I confirmed that oracle-based functions are not called during begin/end block. The PR above should be adequate.

**Comment by alexanderbez** [comment]
Perfect -- this lines up with what I was expecting in the execution flow.
