### ISSUE TITLE
x/oracle: fund reward pool

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#335]
## Summary

The x/oracle module, adapted from Terra's, currently has no direct in-protocol incentivization mechanism. 

In Terra's case, it instead has a "reward pool" that is funded via swap fees. These swap fees go into the oracle's reward pool and then are distributed out to validators/ballot voters in x/oracle.

## Problem Definition

Apart from disincentivization of being slashed if enough ballots are missed in a window, we currently have no direct in-protocol method of incentivization.

## Proposal

Similar to Terra, we should fund the x/oracle's reward pool with funds from the x/leverage module. Namely, we can use a portion of interest accrued on debt (borrows) or even a direct fee on all leverage borrow & lend txs.

Thoughts @toteki @brentxu

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
What denomination should the reward be? If it's `uumee`, then accrued interest is mostly off the table as it accrues in all denoms.

Does the current steup count a ballot with some exchange rates=zero as missed, for slashing purposes?

**Comment by alexanderbez** [comment]
> What denomination should the reward be? If it's uumee, then accrued interest is mostly off the table as it accrues in all denoms.

If can be in `uumee` and other assets such as IBC, i.e. it doesn't have to be limited.

> Does the current steup count a ballot with some exchange rates=zero as missed, for slashing purposes?

You're slashed if you miss enough votes/ballots in a period of time, you can "abstain" from voting without being counted as a miss.

**Comment by alexanderbez** [comment]
My vote is for us to fund the reward pool using interest accrued on debt. These assets are enabled in x/leverage using prices from x/oracle, so to me it makes natural sense for us to reward oracle feeders in the assets they support.

**Comment by toteki** [comment]
Yoted
