### ISSUE TITLE
x/leverage: Queries for frontend support

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#343]
## Summary

For reference, the list of existing queries can always be found in `proto/leverage/v1beta1/query.proto`

We need to add the following queries (feel free to add more in the comments)

- [x] Borrow APY of token -> [PR](https://github.com/umee-network/umee/pull/348)
- [x] Lend APY of token -> [PR](https://github.com/umee-network/umee/pull/367)
- [x] Market Size of an asset -> [PR](https://github.com/umee-network/umee/pull/376/files)
- [x] Available liquidity for borrowing -> [PR](https://github.com/umee-network/umee/pull/379)

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RafilxTenfen** [comment]
I will start doing the borrow APY of token query

**Comment by AgentRoberto** [comment]
We also need:

- [ ] Market Size of an asset
- [ ] Available liquidity for depositing
- [ ] Available liquidity for borrowing

**Comment by alexanderbez** [comment]
@AgentRoberto I just updated the main list in the initial post to keep things tidy.

**Comment by AgentRoberto** [comment]
@alexanderbez By market size we mean the tvl for each asset. Total deposits for an asset, not excluding borrowed funds.

**Comment by toteki** [comment]
Convenient implementation notes:

For market size, it sounds like we can take advantage of the fact that `TotalUtokenSupply = (Module balance + total borrowed) / uToken exchange rate` for a given token and corresponding uToken denom.

Thus
```
// denom = base denomination, e.g. "uumee", uDenom = "u/" + denom
marketSizeCoin := k.ExchangeUTokens(k.TotalUTokenSupply(uDenom))
marketSizeUSD := k.TokenValue(marketSizeCoin)
```

**Comment by toteki** [comment]
Could you specify what is meant by available liquidity for depositing?

**Comment by AgentRoberto** [comment]
> Could you specify what is meant by available liquidity for depositing? @AgentRoberto

This was a mistake, I removed it from the list!

**Comment by RafilxTenfen** [comment]
I will start the "Lend APY of token" in another PR ;)

**Comment by RafilxTenfen** [comment]
Starting the query for Market Size of an asset

**Comment by alexanderbez** [comment]
@RafilxTenfen try just doing `ref: #XXX` in the PR body next time. I think that should do it.

**Comment by RafilxTenfen** [comment]
> @RafilxTenfen try just doing `ref: #XXX` in the PR body next time. I think that should do it.

instead of linking it?

**Comment by alexanderbez** [comment]
I updated #376 to show you what I mean.

**Comment by RafilxTenfen** [comment]
Starting the query for getting the Available liquidity for borrowing of a specific asset
