### ISSUE TITLE
x/leverage: Expand CLI tests for CmdQueryLiquidationTargets and CmdLiquidate

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#350]
## Summary

Current CLI tests (`x/leverage/client/tests/suite.go`) for liquidation-related features are incomplete, because no borrowers can be created which are over their borrow limit during the test.

Current tests do cover situations where no liquidation targets are available.

To fully test these two things, we could decrease the collateral weight of `uumee` mid-test after borrowing, then attempt liquidation. There are not any simple ways to do this, though.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Could we (1) borrow asset, (2) update collateral weight via governance, then (3) attempt liquidate?

**Comment by toteki** [comment]
That would work - would governance update be easy to do during the CLI tests?

**Comment by alexanderbez** [comment]
> That would work - would governance update be easy to do during the CLI tests?

Yes, we just need a short voting period. Then we send a proposal with a deposit, vote and wait enough blocks. You can look at x/gov CLI tests for a reference too.

**Comment by alexanderbez** [comment]
@toteki want me to write up some CLI test utility methods that do this?

**Comment by toteki** [comment]
> @toteki want me to write up some CLI test utility methods that do this?

Definitely - after that I can get the remaining tests in

**Comment by alexanderbez** [comment]
https://github.com/umee-network/umee/pull/355
