### ISSUE TITLE
price-feeder: telemetry + updates

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#378]
1. We should probably gracefully exit instead of just logging a warning message in `checkAcceptList`: https://github.com/umee-network/umee/blob/93239c1a39b002498b2198b29e9547bc4e762657/price-feeder/oracle/oracle.go#L280.

Since operators will probably not be routinely checking their logs, they won't know to update their config until it's too late. @adamewozniak wdyt? If we do, I don't think we can easily just return an error, since `tick` just logs and ignores those. Instead, we might have to use the `Fatal` method on the logger?

2. We should have support for some basic form of telemetry. I propose we use Prometheus. We don't need anything fancy. Just basic metrics. E.g. failed provider call counters, tick duration, tx failure counter, etc...

Look at the SDK for example on how to set this up: https://github.com/cosmos/cosmos-sdk/blob/master/telemetry/metrics.go

**Comment by adamewozniak** [comment]
Not 100% sure about 1 - although I understand why, it could lead to our all validators stopping voting at once when we introduce a new value on the accept list, and then us dropping all exchange rates - especially if validators are manually updating their configs after-the-fact

**Comment by alexanderbez** [comment]
My concern is many of them won't be paying attention. So we could have missing exchange rates for newly supported assets. I guess for now, we can keep the warning 👍

**Comment by adamewozniak** [comment]
Feels like we need some sort of notification service or a way to push new exchange rates to configs, that way we're not waiting on validators
