### ISSUE TITLE
simulator: update MsgSetOrchestratorAddress

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#389]
Currently, multi-seed simulations _can_ fail due to the staking validator set completely changing from what existed at genesis. The reason it can fail is because if the entire validator set changes, the gravity module will not have orchestrator addresses set for them.

We either need to:

1. Add a local x/gravity module simulator implementation that sends a `MsgSetOrchestratorAddress` operation for any given validator that it does not have in its state (of registered orch addresses).
2. OR, last resort, for the staking module simulator to never create new validators.

e.g. https://github.com/umee-network/umee/runs/4793575082?check_suite_focus=true

**Comment by adamewozniak** [comment]
Looks like even with the changes in PR #395, gravity bridge panics on having no validators at some point. Relevant code is in `GetCurrentValset`, called by `EndBlocker.createValsets` : 
```go
validators := k.StakingKeeper.GetBondedValidatorsByPower(ctx)
bridgeValidators := make([]*types.InternalBridgeValidator, 0, len(validators))
for _, validator := range validators {
....
    ibv, err := types.NewInternalBridgeValidator(bv)
    bridgeValidators = append(bridgeValidators, ibv)
}
....
valset, err := types.NewValset(valsetNonce, uint64(ctx.BlockHeight()), bridgeValidators, rewardAmount, *rewardToken)
if err != nil {
   panic(sdkerrors.Wrap(err, "generated invalid valset"))
}
```
Where `types.NewValset` performs a validation of  
```go
if len(b) == 0 {
   return ErrEmpty
}
```

**Comment by alexanderbez** [comment]
Yes, this is exactly the issue, if either (A) the entire validator set changes or (B) is completely empty, albeit less relevant because this would never happen in a real context, the gravity bridge's `GetCurrentValset` would fail.

I'm surprised (B) happens in simulations at all. We should probably raise in issue in the gravity bridge repo re how to handle completely empty validator sets, although I don't think this is as important.

I mainly wanted to address (A) in simulations. Maybe we just don't bother with multi-seed sims  for now :-/

But I would like for us to find a way to address this. /cc @jkilpatr

**Comment by adamewozniak** [comment]
@alexanderbez yeah, doesn't look like multi-seed sims with the gravity bridge are efficient enough
