### ISSUE TITLE
cli: duplicated collect-gentxs command

### ISSUE THREAD

**Issue by facundomedica** [umee-network/umee#394]
It's due to the re-add of the Gravity Bridge's gentx. Should we keep both but rename one of them to `collect-gentxs-gravity`?

```
facundo@Facundos-MacBook-Pro umee % umeed
A daemon and client for interacting with the Umee network. Umee is a
Universal Capital Facility that can collateralize assets on one blockchain
towards borrowing assets on another blockchain.

Usage:
  umeed [command]

Available Commands:
  add-genesis-account Add a genesis account to genesis.json
  collect-gentxs      Collect genesis txs and output a genesis.json file
  collect-gentxs      Collect genesis txs and output a genesis.json file
```

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Ahh good catch! Does the gravity version have it's own command implementation? If so, what are the main differences? I don't see anything specific to message types in the SDK version.

**Comment by facundomedica** [comment]
Judging by what I'm seeing [here](https://github.com/Gravity-Bridge/Gravity-Bridge/blob/main/module/cmd/gravity/cmd/gentx.go#L290) we should be able to just remove it. Gonna double check when I get to my desk and open a PR if needed

**Comment by alexanderbez** [comment]
Yeah, the only main difference is I see is:

```
		// TODO: validate msgdelegatekeys
```

lol
