### ISSUE TITLE
validate-genesis fails when using gentx-gravity

### ISSUE THREAD

**Issue by facundomedica** [umee-network/umee#409]
## Summary of Bug

When using `gentx-gravity` (instead of just `gentx`) we get an error: `must provide genesis Tx with exactly 1 CreateValidator message` (Which happens here: https://github.com/cosmos/cosmos-sdk/blob/master/x/genutil/types/genesis_state.go#L98).

We need to provide our own validate-genesis so it can accept 2 messages, 1 MsgCreateValidator and 1 /gravity.v1.MsgSetOrchestratorAddress.

----

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
@RafilxTenfen or @adamewozniak lmk if either of you would have interest in picking this up. We can pair on it.
