### ISSUE TITLE
x/oracle pre-vote and vote issues

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#416]
## Summary of Bug

There are a few issues with the pre-vote and vote process : 
- [x] 1. The salt we use is too short (should have a minimum required length)
- [x] 2. We have improper salt validation ( must be a hex-encoded string that does not include ":" )
- [x] 3. We have loose validation for exchange rate strings. We should remove `tuplesStr = strings.TrimSpace(tuplesStr)` and make sure that `denomAmountStr` is explicitly _equal to two_ instead of making sure that `denomAmountStr` is not _less than two_ 

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
@adamewozniak what PR addressed #2?

**Comment by adamewozniak** [comment]
@alexanderbez #430, added a test for the ":" character & checked to ensure no error when running `AggregateVoteHashFromHexString` in msg.ValidateBasic
