### ISSUE TITLE
oracle: evaluate Chainlink adapters

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#423]
Chainlink has a slew of premium and trusted "adapters": https://chainlinkadapters.com/

We should evaluate if we should run one or more of these trusted adapters and use them as providers in our price-feeder.

/cc @adamewozniak @dreamcodez

**Comment by alexanderbez** [comment]
For example, it seems Kava uses Binance as the primary adapter and coingecko as the backup: https://docs.kava.io/tools/oracle.html

**Comment by alexanderbez** [comment]
So I was actually slightly wrong. We wouldn't use chainlink as another provider. But rather, we must implement an external provider. I.e., the `price-feeder` tool becomes a chainlink external adapter. So it's more like the current design vs chainlink only.

**Comment by adamewozniak** [comment]
Closing this issue - this originally was supposed to be for us investigating this as an option for calypso, but we're going with the price feeder implementation. Adapters seem to not have enough support for cosmos-native assets. 

Will reopen if the price feeder struggles significantly 😄
