### ISSUE TITLE
x/oracle: remove hard-coded USD exchange rate

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#435]
## Summary

Remove the following from the `x/oracle` module:

https://github.com/umee-network/umee/blob/3d0cddd91b3458350db63865d81e5910a1818a13/x/oracle/keeper/keeper.go#L92-L94

We will support both cosmos native and ethereum stablecoins, which are not always $1

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
Added audit label as this was discussed in TrailOfBits audit
