### ISSUE TITLE
x/oracle: GetSigners should NOT panic on error

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#449]
(found during trail of bits audit)

The leverage module's GetSigners methods for transactions should match oracle module's behavior, panicking when they cannot parse an address.

**Comment by alexanderbez** [comment]
We need to **omit** panics in `GetSigners` for all message types 👍

**Comment by toteki** [comment]
In that case, `x/leverage` is good and `x/oracle` needs the change - I'll change title and label
