### ISSUE TITLE
x/oracle integer overflow

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#492]
## Summary of Bug

Validators may send large exchange rates, crashing other nodes via a panic due an integer overflow when performing ballot arithemetic via sdk.Dec types..

```golang
 for _, v := range pb { 
 	deviation := v.ExchangeRate.Sub(median) 
 	sum = sum.Add(deviation.Mul(deviation)) 
 } 
```

While there are overflow bound checks that exist on individual exchange rate votes, there aren't overflow checks on the computation performed above.

Found during the ToB audit 
Was fixed in an [issue](https://github.com/terra-money/core/issues/667) opened up on Terra Core

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
Terra fixed temporarily by doing 

```
	// The deferred recover here is what they added
	defer func() {
		if e := recover(); e != nil {
			standardDeviation = sdk.ZeroDec()
		}
	}()

	sum := sdk.ZeroDec()
	for _, v := range pb {
		deviation := v.ExchangeRate.Sub(median)
		sum = sum.Add(deviation.Mul(deviation))
	}
	variance := sum.QuoInt64(int64(len(pb)))
	floatNum, _ := strconv.ParseFloat(variance.String(), 64)
	floatNum = math.Sqrt(floatNum)
	standardDeviation, _ = sdk.NewDecFromStr(fmt.Sprintf("%f", floatNum))
	return
```

The error only existed because they were trying to parse `sdk.Dec`, which cannot overflow, into `float64`, which can overflow.

But since we have already removed such parsing by keeping things as `sdk.Dec`
```
	sum := sdk.ZeroDec()
	for _, v := range pb {
		deviation := v.ExchangeRate.Sub(median)
		sum = sum.Add(deviation.Mul(deviation))
	}

	variance := sum.QuoInt64(int64(len(pb)))

	standardDeviation, err := variance.ApproxSqrt()

	if err != nil {
		return sdk.ZeroDec(), err
	}

	return standardDeviation, nil
```
I don't think any changes are required - we're already immune.

Does that look right?

**Comment by adamewozniak** [comment]
> Does that look right?

I'm pretty sure this is an issue, this test panics : 

```golang
func TestPBStandardDeviationOverflow(t *testing.T) {
	valAddr := sdk.ValAddress(secp256k1.GenPrivKey().PubKey().Address())
	exchangeRate, err := sdk.NewDecFromStr("100000000000000000000000000000000000000000000000000000000.0")
	require.NoError(t, err)

	pb := ExchangeRateBallot{NewVoteForTally(
		sdk.ZeroDec(),
		core.MicroSDRDenom,
		valAddr,
		2,
	), NewVoteForTally(
		exchangeRate,
		core.MicroSDRDenom,
		valAddr,
		1,
	)}

	pb.StandardDeviation(pb.WeightedMedianWithAssertion())
}
```

**Comment by adamewozniak** [comment]
> Does that look right?

Need to write tests to make sure this doesn't panic regardless, I'll probably write a `ballot_test.go` before we close this out

**Comment by adamewozniak** [comment]
> > Does that look right?
> 
> I think so, but we need to write tests to make sure this doesn't panic regardless - I'll probably write a `ballot_test.go` before we close this out

Yeah, running this test panics on int overflow : 
```golang
func (s *IntegrationTestSuite) TestBallot_Overflow() {
	valAddr := sdk.ValAddress(secp256k1.GenPrivKey().PubKey().Address())
	exchangeRate, err := sdk.NewDecFromStr("100000000000000000000000000000000000000000000000000000000.0")
	s.Require().NoError(err)

	pb := types.ExchangeRateBallot{types.NewVoteForTally(
		sdk.ZeroDec(),
		"UMEE",
		valAddr,
		2,
	), types.NewVoteForTally(
		exchangeRate,
		"UMEE",
		valAddr,
		1,
	)}

	_, err = pb.StandardDeviation()
	s.Require().NoError(err)
}
```

**Comment by alexanderbez** [comment]
Where does it panic @adamewozniak? `NewDecFromStr` or `StandardDeviation`?

**Comment by toteki** [comment]
Found it - sdk.Dec intentionally stops decimals above a certain size:

```
// bytes required to represent the above precision
// Ceiling[Log2[999 999 999 999 999 999]]
const DecimalPrecisionBits = 60
const maxDecBitLen = maxBitLen + DecimalPrecisionBits
```

then 

```
// multiplication
func (d Dec) Mul(d2 Dec) Dec {
	mul := new(big.Int).Mul(d.i, d2.i)
	chopped := chopPrecisionAndRound(mul)

	if chopped.BitLen() > maxDecBitLen {
		panic("Int overflow")
	}
	return Dec{chopped}
}
```

so for us
```
sum := sdk.ZeroDec()
	for _, v := range pb {
		deviation := v.ExchangeRate.Sub(median)
		sum = sum.Add(deviation.Mul(deviation))
	}
```
That last line can overflow on `Mul`

**Comment by adamewozniak** [comment]
> Where does it panic @adamewozniak? `NewDecFromStr` or `StandardDeviation`?

Panics on `_, err = pb.StandardDeviation()`, as mentioned above by @toteki
