### ISSUE TITLE
x/leverage: clear bad debt addresses which have gained collateral before being swept

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#537]
## Summary of Bug

🐞 🐞 🐞 🐞 🐞 🐞 

Suppose the following sequence of events:
- Borrower A is liquidated to zero collateral, 5 atom borrowed
- Borrower A is registered as a bad debt, to be repaid next endblocker
- Either before end of block, or later if atom reserves are exhausted, borrower A enables additional collateral

After these events, borrower A is still counted as a bad debt address, and `EndBlock` will attempt to repay all of its borrows, even though it is no longer undercollateralized.

Additionally, if borrower A is malicious, it can attempt to lend as much collateral as possible, then borrow as much as possible up to its new borrow limit, before the bad debt flag is cleared. Then `EndBlock` will pay off those debts for free, thus allowing the lent collateral to be withdrawn as well. Borrower A has stolen funds.

🐞 🐞 🐞 🐞 🐞 🐞 

## Le Solution

When sweeping bad debts to repay, clear the bad debt flag from any address that has nonzero collateral before action. `GetBorrowerCollateral(ctx,addr).IsZero()` can be used for this.

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Yikes, very buggy indeed. Good catch. The user A here would have to submit multi-msg txs to execute this though, right?

**Comment by toteki** [comment]
They'd need the Liquidate + Lend/Enable + Borrow to occur before the next EndBlock and in that order -  or if reserves are exhausted (so bad debts aren't all repaid on the next EndBlock) then they could do it at their leisure.

An attacker's main difficulty would be intentionally achieving bad debt status without being liquidated by anyone first, but after that it's doable.

**Comment by alexanderbez** [comment]
Yeah, that would be difficult but possible. Glad the fix is easy.

Do you think we have other edge cases like this? Would be neat to have invariants or simulations somehow catch this...
