### ISSUE TITLE
price-feeder: change to use last traded price volume-weighted

### ISSUE THREAD

**Issue by RafilxTenfen** [umee-network/umee#542]
## Summary

- Today in the providers we use the last traded price, the proposal is for us to use a volume-weighted price for the trades that occur in the last N minutes   

## Problem Definition

- We could use this feature to have a more concise price using all the traded made by that ticker in the last N minutes 

## Proposal

- The idea of this implementation comes from [terra oracle](https://github.com/terra-money/oracle-feeder)
   - They maintain all the trades that happen in the last 60 min (don't know why soo much)
   - Filter for the ones that happened last 3 minutes 
   - If it has one it uses `tvwap(time volume-weighted average price)`
   - in the end, it is `sum(volume * price) / (total volume)`

- For this to happen we need to: 
   - Change the Provider structs to store all the trades that happened in the last N minutes 
   - Compute the price taking into consideration all the trades that happened in all the providers in the last N minutes
   

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
Right direction, although maybe we don't store the last 60, maybe just the last 10? This should probably be implemented after we switch to websockets, seems like it'd be easier to do

**Comment by adamewozniak** [comment]
note, the last bits we need here are the resolution to [this comment](https://github.com/umee-network/umee/pull/592#discussion_r818084703) and the addition of faulty price feeder detection for tvwap. 

cc : @RafilxTenfen

**Comment by adamewozniak** [comment]
Closing this since #609 & #610 have been merged in - will address problems with warning messaging in #619
