### ISSUE TITLE
Umee v3 (Calypso) Upgrade Tracking

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#603]
Mainly creating this issue as a brain dump of things to keep in mind when getting ready for the Umee v2 (Calypso) on-chain upgrade:

- [x] SDK v0.46 breaking changes
- [x] Dep updates
   - [x] IBC (state-machine breaking patch)
   - [x] TM v0.35
   - [x] SDK v0.46
- [x] Upgrade handler

**Comment by toteki** [comment]
SDK 0.46 required for _message prioritization_ (umee #510 and [peggo #179](https://github.com/umee-network/peggo/issues/179))

**Comment by toteki** [comment]
[ibc-go](https://github.com/cosmos/ibc-go) 3.0.0 is out now, but we should do it simultaneously with [SDK 0.46](https://hub.cosmos.network/main/roadmap/cosmos-hub-roadmap-2.0.html)

This contains _interchain accounts_ functionality, which we won't be directly using yet but might allow us to more easily develop meTokens (from the whitepaper) and deploy the relevant upgrade when the time comes. That's not in scope now though.

**Comment by toteki** [comment]
Public testnet will actually go through the upgrade procedure (NOT including SDK 0.46) starting from `1.0.x` to `2.0.x` in order to more closely simulate what we'll be doing in reality.

**Comment by toteki** [comment]
Public testnet will actually go through the upgrade procedure (NOT including SDK 0.46) starting from `1.0.x` to `2.0.x` in order to more closely simulate what we'll be doing in reality.
