### ISSUE TITLE
Add gate as a provider for the price feeder 

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#604]
## Summary

We need to add gate as a provider for the price feeder, to meet our minimum of 3 providers per token for UMEE.

Ticker API : https://www.gate.io/docs/websocket/#ticker-api
Kline API : https://www.gate.io/docs/websocket/#kline-api

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
We should hopefully have coinbase soon too...they're dragging their tails
