### ISSUE TITLE
x/leverage: accepted -> unaccepted assets behavior

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#724]
Suppose that a user has deposited `1000 uabcd` and received `800 u/uabcd` (a token:uToken exchange rate of `1.25`). They may or may not have enabled `uabcd` as collateral.

Other users may have borrowed `uabcd` as well.

Then, the leverage module's token registry is updated, and for whatever reason, `uabcd` has been removed as an accepted asset.

EDIT: Oracle prices will still be available for symbol `ABCD`

## Causes

An asset could be removed from the accepted asset list in two scenarios:

- Governance decision (token registry update made with intent to remove asset)
- Accident (token registry update missing an entry)

## Consequences

| How should this scenario be treated? | What changed to the code are required? |
| - | - |
| User should be able to withdraw `uabcd` that has been lent or set as collateral if no borrow limit concerns overrule. | `WithdrawAsset` and `ExchangeUToken` need to function for assets which are not in the token registry, but whose uToken exchange rates still exist in store, as would be the case. |
| Users should be able to repay, but not borrow, `uabcd` | Alter `RepayAsset` |
| User should be able to disable, but not enable, `uabcd` as collateral if no borrow limit concers overrule.| Rearrange `SetCollateralSetting` |
| Calculations involving `BorrowLimit`, `LiquidationLimit`, or `BorrowedValue` should omit unregistered tokens from the total USD value, or even fail altogether. | TBD below |
| Without oracle prices, liquidations of `uabcd` borrows or collateral are not possible. Liquidation of the borrower's other denoms of debt and collateral may be possible. | TBD below |
| `EndBlocker` had better not crash | No changes - interest iterates over accepted assets only. |

Inevitably, anyone who was using `uabcd` as collateral may instantly drop below their borrow or liquidation limits. This would also happen if an asset's collateral weight were reduced or zeroed by governance, an action which would occur before intentional (but not accidental) versions of the scenario.

Anyone borrowing `uabcd` could be off the hook if `uabcd` no longer contributes USD value to their borrowed value. Alternately, users could be prevented from borrow-limit-dependent actions (withdraw, borrow, unset collateral) until all their borrows containing unaccepted asset `uabcd` have been repaid. This is cleaner, as long as `uabcd` can still be obtained.

## Decisions

| Question | Initial Conclusion |
| - | - |
| Should `WithdrawAsset` allow the retrieval of `uabcd` by exchanging `u/uabcd` uTokens? | Yes, users must be able to recover lent assets. However, see borrow limit decision first. |
| Should `RepayAsset` work for `uabcd` debts? | Yes, always. |
| Should `LendAsset` work for `uabcd`? | No. |
| Should `BorrowAsset` work for `uabcd`? | No. |
| Should `LiquidateBorrow` work for `uabcd` _repay_ denomination? | No. Oracle prices required. |
| Should `LiquidateBorrow` work for `u/uabcd` _reward_ denomination? | No. Oracle prices required. |
| How should `BorrowedValue`, `BorrowLimit` and `LiquidationLimit` be calculated when collateral contains `u/uabcd`? | Queries can be allowed to fail. `BorrowAsset` and `SetCollateralSetting(any_denom, false)'s` borrow limit check should fail, stopping the transaction. Withdraw and Liquidation are more complicated - see below. |
| How should `WithdrawAsset` work? | The withdraw denom can either be `uabcd` or some accepted asset. In both cases, a withdrawal is _definitely_ safe if the user has no `uabcd` borrows, and also their collateral value after the transaction, even excluding contributions from `u/uabcd` collateral, would still result in a healthy borrow limit. |
| How should `GetEligibleLiquidationTargets` and `LiquidateBorrow` handle `uabcd` in collateral value calculations?| If we allow the calculations to fail, then a user can exempt themselves from liquidation forever by holding onto some collateral in a non-accepted denom. If we allow the calculations to succeed, then we must be treating `uabcd` collateral as having zero USD value. This could cause liquidations but seems to be the better option. |
| How should `GetEligibleLiquidationTargets` and `LiquidateBorrow` handle `uabcd` in borrowed value calculations?| If we allow the calculations to fail, then a user can exempt themselves from liquidation forever by holding onto some debt in a non-accepted denom. We must count borrowed but non-accepted assets as contributing zero to borrowed value during liquidation, and allow the function to proceed. |
| Any interactions with `SweepBadDebts`? As a reminder, this is when a borrower has nonzero debt and zero collateral after a complete liquidation, and the system steps in to pay off the remaining debts. | It looks like nonzero `uabcd` collateral will prevent debt from being flagged, even if all other collateral is liquidated. Minor issue. |

## User Perspective

Under initial conclusions, here is how to safely exit a complex position in `uabcd`.
- Repay all `uabcd` borrows, re-enabling `BorrowedValue` calculations.
- Withdraw all `uabcd` collateral after ensuring healthy borrow limit.
- Withdraw any `uabcd` lent by turning in `u/uabcd`.

## Attacker Perspective

Who can benefit from an asset going dark?
- Liquidators in general (same as a governance reduction or collateral weight, or a price drop).
- Anyone who can borrow `uabcd` without repaying it, but still get their collateral back.

## Final Note

We should REALLY avoid doing this (blacklisting an accepted asset), but the code can be made attack-proof at least.

**Comment by adamewozniak** [comment]
Important to note that currently [we don't remove](https://github.com/umee-network/umee/blob/d9903f72d511e2e50b0a27527906d5534366cbbb/x/oracle/keeper/hooks.go#L57) required exchange rates from the x/oracle `AcceptList` if tokens are removed via governance @toteki

**Comment by toteki** [comment]
That helps - some of the decisions might be simplified if oracle prices can still be counted on.
