### ISSUE TITLE
Price feeder limitations

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#792]
## Summary

Our price feeder has a few limitations that will affect our ability to support coins in the long term. 

## Problem Definition

Our price feeder is limited by : 

* The Three-Provider Rule

Currently for the price feeder to vote on an exchange rate, it has to have at least three providers. This is to avoid scenarios where one provider goes down and we become dependent on another, which might malfunction or have low enough volume to be manipulated. This creates a pretty big issue in the cosmos ecosystem, because there are quite a few tokens only on one or two exchanges, such as [osmosis](https://www.coingecko.com/en/coins/osmosis) and [juno](https://www.coingecko.com/en/coins/juno-network). 

So, the right number of providers to require for an exchange rate is the number of providers which list that rate. 

* Osmosis API limitations

Certain APIs have stale data, such as the [osmosis API](https://api-osmosis.imperator.co/swagger/) we're using, which consistently returns historical data from ~6-4 minutes ago. The price feeder only uses the most recent information, so it filters out any candles that occurred before a certain amount of time, [currently set to three minutes](https://github.com/umee-network/umee/blob/2343d707c2157da6f6887956bb21cf21abb1ff04/price-feeder/oracle/util.go#L18). So, this rule keeps us further from supporting coins that are only on osmosis.

So really, the right number of providers to require for an exchange rate is the number of providers which list that rate, and has an up-to-date, low-latency API available.

## Proposal

We should : 

1. Use an external data source (or sources) like coingecko to determine the amount of exchanges on which a pair is listed, and require that amount instead of the default of "3".
a. Need to decide on what to do in the case that these APIs fail; do we require 3 as the default or are we more lenient to support those currencies which only have one or two exchange rates? 

2. Find a way to get more recent pricing data from osmosis. This would probably require us to run our own osmosis node & API instead of using imperator's.
a. Still need to look into endpoint limitations. If this data isn't accessible, how do we determine what is an acceptable time period per provider?

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RafilxTenfen** [comment]
About the proposal (1) We also could check on our own the number of exchanges on which a pair is listed using the providers `GetAvailablePairs` function ^^

**Comment by adamewozniak** [comment]
Adding @rbajollari onto this since he's working on using coingecko for #1 🥳

**Comment by RafilxTenfen** [comment]
> 1. Use an external data source (or sources) like coingecko to determine the amount of exchanges on which a pair is listed, and require that amount instead of the default of "3".

Would be good to have at least 2 sources of exchanges... to avoid things like [this](https://github.com/umee-network/peggo/issues/181) again

**Comment by adamewozniak** [comment]
Closing this out 🥳
