### ISSUE TITLE
add CosmWasm

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#802]
## Summary

We need to investigate how easy / difficult it would be to add [CosmWasm](https://cosmwasm.com/) to our chain, and experiment with how we would use it.

@RafilxTenfen will be doing the initial investigation.

### What we need to add cosmwasm
- [ ] #1189 
- [ ] #1190
- [ ] #1191

**Comment by RafilxTenfen** [comment]
https://blog.cosmos.network/cosmwasm-for-developers-7640ee38430f

"The provided [cosmwasm module](https://github.com/cosmwasm/wasmd/tree/master/x/wasm) is a minimal, unopinionated implementation of bindings between the SDK and the smart contract VM. It is embedded in [wasmd](https://github.com/cosmwasm/wasmd), which is a fork of gaiad with x/wasmd added. It takes care of all the implementation details, but leaves the field open for you to fork this repo and add custom business logic around it."

**Comment by RafilxTenfen** [comment]
I will try to do something like [Juno](https://github.com/CosmosContracts/juno/pull/71)
