### ISSUE TITLE
Umeed memory leak suspected on testnet

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#818]
## Summary of Bug

The `umeed` process seems to have a memory leak, taking up .1 gigs ~ every 5 mins.

We should be able to use the `pprof` tool to check this out

## Version

V2.0.1

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
Here's our memory allocation after a small while : 
![profile001](https://user-images.githubusercontent.com/29418299/163821831-bb71cb86-ddcd-4f49-a381-7a604c2d81ae.png)

Running these commands in [this branch ](https://github.com/umee-network/umee/tree/woz/dnm-pprof):
`go tool pprof http://localhost:6060/debug/pprof/heap`
`png`

**Comment by adamewozniak** [comment]
Need to run a testnet node with pprof running to better understand this

**Comment by adamewozniak** [comment]
Running a testnet node with pprof atm - we're going to take a few screenshots and see how it does over time, this may not be a memory leak since it's anecdotally going down

**Comment by adamewozniak** [comment]
Update on this, might just be performance issues. Not seeing this on full nodes running the same binary, so going to take some metrics and then point the faucet -> full node, then try frontend -> full node. 

At least if they're pointed at full nodes instead of a validator, we won't halt the chain

**Comment by adamewozniak** [comment]
@dreamcodez what did we decide on this, can we close this issue? 

iirc we haven't seen this memory issue in a while, and it's rather issues with high traffic

**Comment by toteki** [comment]
Changed the issue name back to memory leak since that's what the most of the discussion was on. (That way we can find it if looking back on old issues.)

We can probably close now, since we haven't been able to observe/reproduce it since.

**Comment by adamewozniak** [comment]
Closing due to inability to observe & reproduce. Ty for the naming change @toteki 😄
