### ISSUE TITLE
x/leverage: overly restrictive behavior in MsgLiquidate's ValidateBasic

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#828]
Documented behavior of `MsgLiquidate` says it should interpret zero reward amount as "no user-set minimum".

Instead, the following code rejects Amount = 0
```go
// x/leverage/types/tx.go
// func (msg *MsgLiquidate) ValidateBasic()
	if asset := msg.GetReward(); !asset.IsValid() {
		return sdkerrors.Wrap(ErrInvalidAsset, asset.String())
	}
```

The desired behavior for amount=0 can be reproduced by setting amount=1, but we should preferabkly fix the ValidateBasic.

**Comment by toteki** [comment]
Misdiagnosis - it's not asset.IsValid(), because that accepts zero, but something's stopping CLI liquidation with 0 reward
```
Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: 0ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2: invalid asset: invalid request
```

**Comment by robert-zaremba** [comment]
`Coin.IsValid()` rejects only negative amounts. So yes, there must be other error.

**Comment by robert-zaremba** [comment]
Do you think we need it for mainnet?

**Comment by toteki** [comment]
Better to fix this now than have to push a state-breaking fix later, since it's a small difference.
