### ISSUE TITLE
use prerelease tags

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#879]
It would be preferable to have out mainnet start on a release labeled `v2.0.0` even though we've already published such a release.

While convexity's mainnet launch is still far off, we could duplicate the following tags+releases then delete the originals:

`v2.0.0` -> `v2.0.0-beta1`
`v2.0.1` -> `v2.0.0-beta2`

Then it would be possible to use the `v2.0.0` tag properly when the time comes.

**Comment by robert-zaremba** [comment]
You can't do it. Go module caches the tags once they are used. So once the tag is out, we can't reassign it.
Instead, if we want, we can do `v2.1.0` for mainnet. Is anyone building tools based on our API?

**Comment by toteki** [comment]
Doubt there are external tools, but I'd prefer we stick to semver - no backwards incompatible changes from 2.0.0 to 2.1.0, and we're definitely going to have some of those between 2.0.0 and mainnet.

I'm thinking the best option is to make the convexity mainnet launch `v3.0.0` so mainnet skips v2 altogether.

**Comment by robert-zaremba** [comment]
yes, we will use `v3` for mainnet.
