### ISSUE TITLE
Research - meTokens

### ISSUE THREAD

**Issue by khoerling** [umee-network/umee#891]
Let's start brainstorming how MeTokens would be implemented before cutting any code.  Can we offer Liquid Staking without the risks?  Can we learn from Osmosis?

**Comment by toteki** [comment]
Current state of things:
- Use existing staking derivatives when possible (less effort, doesn't split that token's staking derivative market)
- Basically add them as an accepted asset that can be lent & collateralized, but not borrowed
- Hook them up to their associated base asset's oracle exchange rate

**Comment by robert-zaremba** [comment]
And one more requirement:
* learn from Luna drama

**Comment by robert-zaremba** [comment]
Osmosis is doing internal lending product, not cross chain
