### ISSUE TITLE
x/leverage: Support Lending Assets

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#91]
## Summary

Have the ability for `x/leverage` to support users lending allow-listed tokens where a minted "u" token is derived of equal amount.

Note, without an oracle in place, all integration tests should be done with borrowing and lending with internal tokens.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
With the exception of CLI support, which has its own issue (#94), this is complete.
