### ISSUE TITLE
umeed export does not go to stdout, instead goes to stderr

### ISSUE THREAD

**Issue by dreamcodez** [umee-network/umee#914]
## Summary of Bug

umeed export does not go to stdout, instead goes to stderr.

## Version

Please provide the output of the following commands:

- `$ umeed version` -> `2.0.2`
- `$ go version` -> `N/A github standard binary release`
- `$ uname -a` -> `Linux cope 5.13.0-1024-gcp #29~20.04.1-Ubuntu SMP Thu Apr 14 23:15:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

## Steps to Reproduce

`umeed export > mygenesis.json`

Must (to get it to work) do:

`umeed export 2> mygenesis.json`

This behaviour seems non-standard as terra exported to stdout :\

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dreamcodez** [comment]
Turns out I think it is working except we use stderr instead of stdout? testing...

**Comment by RafilxTenfen** [comment]
It was [fixed](https://github.com/cosmos/cosmos-sdk/pull/11844)

**Comment by RafilxTenfen** [comment]
Do we need to wait for v0.46.0 to get the fix? 
@adamewozniak @toteki

**Comment by toteki** [comment]
Looks like 0.46 will fix this issue automatically, but in the meantime if we just need the file we can get it from stderr.
