### ISSUE TITLE
Update ADRs for borrow utilization guard

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#926]
Sytem is at risk when the collateral is heavily utilized by the borrowers. In case of the bank run liquidators will have a risk of not being able to cash out and lenders will loose the money.
Solution: will be discussed in ADR.
![Screenshot_20220519_211858](https://user-images.githubusercontent.com/811701/169418810-3dde91b8-cf3d-4347-9020-89c900de876b.png)

**Comment by hjorthjort** [comment]
Won't a `MaxBorrowUtilization` parameter have a similar effect as if all the collateral has simply been borrowed? I understand that this guarantees that there is some collateral for liquidators to take hold of (because it has not all been lent out) but wouldn't liquidations then violate this parameter? Or is the idea that the parameter only blocks new borrows, not liquidations? Put otherwise: is `BorrowUtilization <= MaxBorrowUtilization` invariant or not?

**Comment by toteki** [comment]
Liquidation would bypass `MaxBorrowUtilization`, new borrows and withdrawals would be restricted. (Withdrawing from the lending pool while borrows remain constant has the effect of increasing utilization %)

So it wouldn't be an invariant.

Prioritizing liquidators allows the system to respond to price swings before it's too late - consider two scenarios:

> Price of a single asset `A` is skyrocketing. Users who borrowed it are seeing their borrowed value rise in relation to collateral value. A healthy liquidation requires the liquidator repay asset `A` and receive any number of collateral assets `A,B,C,D` to resell.

- In this case there is no serious rush for lenders to withdraw any of the token types.
- For borrowers who have borrowed multiple tokens (e.g. `A` and `C`), the liquidator could technically choose to repay either one.

> Price of a single asset `B` is crashing. Users who collateralized it are seeing their collateral value drop in relation to borrowed value. Additionally, lenders who simply supplied it are seeing the USD value of their holdings decrease. A healthy liquidation requires the liquidator repay assets `A,C,D` and receive collateral asset `B` to resell.

- In this case, there will be a rush for lenders to withdraw `B`. Liquidators must also be able to receive and resell `B` quickly, or they see a loss in value as the price of their reward continues to drop.
- If `Collateral Weight` for asset `B` is 70%, then the liquidator needs to be able to liquidate collateral `B` faster than `borrowed:collateral` can rise from 70% to 100%. Anything higher will stress reserves by causing bad debt repayments.
- If `Liquidation Incentive` for asset `B` is 10%, then liquidator needs to be able to resell reward `B` faster than its price can drop from 110% of the repaid value to 100%.
- If `Max Borrow Utilization` for asset `B` is 80%, then there is a buffer of 20% of supplied `B` which is guaranteed to be available to liquidators even if `B` borrowing was at its peak before the crisis. Exhausting this buffer would not completely solve the problem (80:20 is fairly high). Also, some users repaying `B` while the price is low would repair the buffer slightly.
- For borrowers who have collateralized multiple tokens (e.g. `B` and `C`), the liquidator could technically choose to receive either one as a reward. They might even prefer `C`, whose price is not dropping. This means that if the `Max Borrow Utilization` of `C` is 70%, an additional 30% of the value of supplied `C` in the system contributes to the buffer, assuming enough of the same users who collateralized `B` also collateralized `C`.

Overall this is a fairly complicated picture, `MaxBorrowUtilization` will do a lot to ensure liquidators can operate swiftly, which protects reserves. Increased diversity of assets used as collateral will also help, and there is some involvement from `Collateral Weight` and `Liquidation Incentive`.

Lenders aren't as easy to protect from bank runs though - this mostly covers liquidation.

**Comment by robert-zaremba** [comment]
> If combined with other countermeasures (e.g. locking collateral with unbonding periods in x/incentive module), the likelihood of a bank run reaching 100% utilization (where no more withdrawals can happen) will be nearly eliminated.

That's a hope.

**Comment by robert-zaremba** [comment]
>  Or is the idea that the parameter only blocks new borrows, not liquidations?

It won't block liquidations. Liquidations must never be blocked.
