### ISSUE TITLE
x/leverage: Implement gRPC API Routes

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#93]
## Summary

As `x/leverage` gets fleshed out, we'll need to support and provide gRPC queries for relevant business logic.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
Done, with the exception of #343 and a supporting query for #229
