### ISSUE TITLE
Price feeder dependency conflict issues

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#954]
## Summary

Currently our backporting process for the price feeder & the umeed binary means that there is a diff between the two projects, which causes conflicts & a bad experience managing deps. Super open to solutions here.

## Problem Definition

This is an issue because the price feeder's import of the `umee` package uses this replace directive : 

```
github.com/umee-network/umee/v2 => ../
```

Originally this was intended to resolve the issue where our price feeder deps would have to be updated to the latest commit whenever proto files changed, but now since the version of `umee` in the `price-feeder/release/0.x.x` branch differs than the version of `umee` in `/release/x.x.x/` & in `main`, dependency conflicts like this happen : 

https://github.com/umee-network/umee/pull/952

Essentially, the easiest fix for this is to create a new release branch, which is not ideal, especially if we expect to stay on one major version for a long amount of time. 

## Proposal

I propose that we either : 

1. Move off of separated out release branches / backporting processes, so that the version of `umee` that the price feeder is importing is always the most up-to-date
2. Remove the replace directive 

Alternatively, we could: 
1. Backport all `umee` dependency changes to the price-feeder branch, but this would be pretty bothersome 
2. Move the price-feeder into its own repository, which then would import the latest RC 

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
I'm in separate repo gang, since that would allow us to manage dependencies easily in the `umee repo -> pf` direction. 

I think the only circular (pf -> umee) imports are centered around tests, like in the e2e suite. There would be a bit of maneuvering if we needed to update them both at once, but other scenarios should be easier.

**Comment by brianosaurus** [comment]
Ha!

I just wrote this issue:

https://github.com/umee-network/umee/issues/955

I've just run into a similar problem on this PR

https://github.com/umee-network/umee/pull/935

**Comment by adamewozniak** [comment]
We'll move the price feeder to a separate repo after the convexity launch. Don't want to add unnecessary nuance this late in the game

**Comment by robert-zaremba** [comment]
> Remove the replace directive

I don't think it will help. Import paths still need to use `vX` if we use version >=2

**Comment by robert-zaremba** [comment]
Can we close this issue? I think it's done.
