### ISSUE TITLE
Move Umee proto files into a v2 directory in the repo

### ISSUE THREAD

**Issue by brianosaurus** [umee-network/umee#955]
## Summary

Our Umee proto files are in a directory hierarchy under v1; however, they create go modules labeled as v2. We should fix this.
## Problem Definition

We want this change to keep things consistent across our codebase.

## Proposal

Move everything from -> to
```
umee/proto/umee/leverage/v1 -> umee/proto/umee/leverage/v2
umee/proto/umee/oracle/v1 -> umee/proto/umee/leverage/v2
```

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
Proto version (v1) is separate from go module version.

For example, when we release `3.x.x`, go mod's requirements on semantic versioning will require we change our `v2` import paths to `v3`.

On the other hand, proto files only need a version bump on proto-breaking changes (which we're ignoring now to keep v1, but should be rare or never post release).

**Comment by robert-zaremba** [comment]
In general, proto should be as stable as possible, ideally we don't have v2 anytime soon.
