### ISSUE TITLE
Add Swagger to Umeed

### ISSUE THREAD

**Issue by brianosaurus** [umee-network/umee#957]
## Summary

Turn on and customize swagger endpoint for Umeed

## Problem Definition

Swagger is a self-documenting system that is used to document cosmos nodes' protopuf APIs. Turn this on so that developers have a clearer understanding how to develop against Umeed.

## Proposal

Examine the Regen and Axelar Makefile systems to copy best-in-class swagger implementations.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment]
Cosmos SDK has swagger integration in a docker file.

**Comment by dreamcodez** [comment]
any updates on this? @brianosaurus @robert-zaremba

**Comment by robert-zaremba** [comment]
I didn't work on this task.
