### ISSUE TITLE
x/leverage: Integration Tests

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#96]
## Summary

Ensure we have sufficient coverage and implementation of integration tests of `x/leverage`, where the integration tests cover borrowing and lending.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toteki** [comment]
Note: Except for oracle-calculated borrow limits (#213), this is complete. Closing issue.
