### ISSUE TITLE
x/leverage: Integrate Oracle

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#97]
## Summary

A stub placeholder for oracle integration.

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
which oracle you looking at adding?

**Comment by alexanderbez** [comment]
Band I think. That or implement our own like Terra did.

Thoughts? 

TBH, I really have zero idea how to integrate or use an external oracle like Band.

**Comment by marbar3778** [comment]
Band is more like chainlink. While they are useful as a secondary source of data, since app specific chains have their own validator sets this could be passed on to them as well. Either a mandatory job, like terra, or opt in to increase the profitability of running a validator. 

I would start with using my validator set before going external.

**Comment by alexanderbez** [comment]
I'm not sure I follow....we just need an oracle to get price data. Where do validators come into play here?

**Comment by marbar3778** [comment]
> Where do validators come into play here?

Validators are your oracles in the terra design.

**Comment by alexanderbez** [comment]
Right, exactly. But what I was referring to was this statement:

> While they are useful as a secondary source of data, since app specific chains have their own validator sets this could be passed on to them as well.

What do you mean here? I don't follow.

**Comment by marbar3778** [comment]
Band oracles are good as an additional set of oracles, but it's better, IMO, to boot strap oracles with your validators at first.

**Comment by alexanderbez** [comment]
I see. This is good to know! Any chance you can summarize why this is?

**Comment by marbar3778** [comment]
For no added cost, or overhead of the team behind the product, you get oracles. You can slash these oracles and handle any custom logic. When starting a new chain, sometimes you want this fine grain control. I'm not sure about band, but with chainlink there is an added cost to users and the team behind the project. You are also confined to what they offer and their data types.

**Comment by alexanderbez** [comment]
Sounds like we might just want to use our own oracle then.

**Comment by alexanderbez** [comment]
@justyntemme I've taken a look at Terra's [Oracle](https://docs.terra.money/Reference/Terra-core/Module-specifications/spec-oracle.html) spec and I think we can leverage this for our `x/oracle` module implementation.

However, I believe we need just a few changes compared to their approach:

- Combine the `price-server` and `feeder` into a single binary/program and implemented in Golang as opposed to JS. We'll have a goroutine for actually getting the prices and another goroutine that submits the txs.
- We can use Terra's `x/oracle` but we need to evaluate what is implicit or hard-coded into their implementation that may not be applicable for us. For example, their docs state prices are fetched for the exchange rate of LUNA, but we'll most likely want to know the exchange rate by USD*.
- Evaluate their "Compute Cross Exchange Rate" and if we need it. If so, can or should we simplify it? i.e. do we need `ReferenceUSD*`? From what I can tell, this is mainly used for the rewarding logic.
- I think we should only support `MsgAggregateExchangeRate(Pre)Vote`, i.e. not allow individual price updates.

**Comment by sergecao** [comment]
Thank you for  this information. I needed it.  How can i buy tokens  of  Umee ?
